### ISSUE TITLE
To anyone who installed Rust via homebrew

### ISSUE THREAD

**Issue by qbraksa** [google/xi-editor#1]
Apparently installing Rust via Homebrew installs the 1.3 version, which causes `xcodebuild` to return the following error.  

```
Compiling xi-rope v0.0.0 (file:///Users/xyz/dev-lab/xi-editor/rust/rope)
   Compiling serde v0.7.0
   Compiling winapi-build v0.1.1
   Compiling num-integer v0.1.32
rope/src/tree.rs:445:1: 451:2 error: the associated type `<N as tree::NodeInfo>::L` may not live long enough [E0309]
                     ...
``` 

**The solution** was to install Rust from the official website obviously. 

It's definitely my mistake, but I never really installed/used Rust before ... 

(I thought about submitting a PR to explicitly specify a minimum Rust version ... but again I don't know enough about Rust to know which version would be required)

**Comment by raphlinus** [comment]
I believe this is probably https://github.com/rust-lang/rust/issues/23442, which seems to have been fixed in 1.4. I'm trying not to use bleeding-edge features, but there are other 1.4-isms when you get past that, like the use of Vec::split_off (a much nicer API than doing it by hand).

I'll probably update the README to recommend 1.8, which is what I'm building against.

**Comment by caipre** [comment]
Homebrew should install the latest stable release, which is 1.8.0 as of April 14. You may want to run `brew update`.

http://braumeister.org/formula/rust

**Comment by xpe** [comment]
FWIW, `brew install rust` was good enough for me just now. (I update it often.)

**Comment by frewsxcv** [comment]
Yes, installing Rust on Homebrew should install 1.8. Here's the formula for reference:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/rust.rb

**Comment by tommiv** [comment]
Actually, current 1.8 stable doesn't work for me. Logs are:

```
Compiling num-traits v0.1.32
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.6
   Compiling xi-unicode v0.0.0 (file:///Users/tommi/Dev/xi-editor/rust/unicode)
error: can't find crate for `std` [E0463]
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: can't find crate for `std` [E0463]
error: aborting due to previous error
error: can't find crate for `std` [E0463]
error: aborting due to previous error
error: Could not compile `num-traits`.
```

```
tommi@avalon:~/Dev/xi-editor|master⚡
⇒  rustc --version
rustc 1.8.0
tommi@avalon:~/Dev/xi-editor|master⚡
⇒  which rustc
/usr/local/bin/rustc
tommi@avalon:~/Dev/xi-editor|master⚡
⇒  brew info rust
rust: stable 1.8.0 (bottled), HEAD
Safe, concurrent, practical language
https://www.rust-lang.org/
Conflicts with: multirust
/usr/local/Cellar/rust/1.7.0 (10,323 files, 228.2M)
  Poured from bottle
/usr/local/Cellar/rust/1.8.0 (9,398 files, 234.0M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rust.rb
==> Dependencies
Build: cmake ✔
Required: pkg-config ✔, openssl ✔, libssh2 ✔
Optional: llvm ✘
==> Options
--with-llvm
	Build with brewed LLVM. By default, Rust's LLVM will be used.
--HEAD
	Install HEAD version
==> Caveats
```

Maybe it's `num-traits` package incompatibility?

**Comment by raphlinus** [comment]
@tommiv I'm not expert on such things, but looks like something is wrong with your rust install. The `num-traits` version is the same as in my (working) build. FWIW, I use multirust.

**Comment by rkusa** [comment]
I am getting the same error (using homebrew Rust): `error: can't find crate for `std` [E0463]`. According to a quick search, this error seems to be related to cross platform compilation, i.e., it tries to compile against an architecture its std is not compiled against. But I can be wrong on this.
Anyway, opening XCode and hitting Run works fine (instead of using `xcodebuild`).

**Comment by MarloweW** [comment]
Got same error as @rkusa got.

**Comment by zyanho** [comment]
#4  same issue

use to build
```
xcodebuild -scheme XiEditor 
```
instead of just using xcodebuild

**Comment by tommiv** [comment]
@zyanho 
Still doesn't work, I'm afraid.

```
⇒  xcodebuild -scheme XiEditor
xcodebuild: error: The project named "XiEditor" does not contain a scheme named "XiEditor". The "-list" option can be used to find the names of the schemes in the project.
```

and xcodebuild -list says that there is no schemes in project:

```
tommi@avalon:~/Dev/xi-editor|master⚡
⇒  xcodebuild -list
Information about project "XiEditor":
    Targets:
        XiEditor
        xicore
        XiEditorTests
        XiEditorUITests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    This project contains no schemes.
```

**Comment by zyanho** [comment]
you scheme is not listed, because the scheme file not create. 
you have two options to fix it.
1. use xcode.app(not command line) to build and it could autocreate scheme that xcodebuild could use it.
2. use facebook's xctool to instead of xcodebuild. this tool could autocreate scheme. just brew install xctool

hope to help

**Comment by tnguyen14** [comment]
@zyanho I followed your second suggestion, but got the following error instead:

```
:; xctool -scheme XiEditor
ERROR: Cannot find schemes. Please consider creating shared schemes in Xcode.

TIP: This might happen if you're relying on Xcode to autocreate your schemes
and your scheme files don't yet exist.  xctool, like xcodebuild, isn't able to
automatically create schemes.  We recommend disabling "Autocreate schemes"
in your workspace/project, making sure your existing schemes are marked as
"Shared", and making sure they're checked into source control.
```

**Comment by raphlinus** [comment]
I just pushed a fix which should make plain xcodebuild work again, specifically the "can't find crate for `std`" error.

**Comment by tnguyen14** [comment]
Thanks @raphlinus, now the build step succeeded!

However, when trying to open the app, I got another error:

```
:; open build/Release/XiEditor.app
LSOpenURLsWithRole() failed with error -10825 for the file /Users/tnguyen/dev/xi-editor/build/Release/XiEditor.app.
```

If this is unrelated to this thread, I could open a new issue for it. Sorry to spam everyone else.

**Comment by tnguyen14** [comment]
Trying to open it with Finder says that the app requires 10.11, and I have 10.10. So it's a separate issue.

**Comment by leavengood** [comment]
@qbraksa Can you close this issue then? I think the issues with the Rust from Homebrew have been resolved.

@tnguyen14 This project uses the latest Swift so it needs 10.11 (El Capitan) to run. I have not upgraded myself yet, so I feel your pain. But I intend to upgrade soon and I would recommend the same to you. Also another front-end was recently started using a pure Rust library which you could also try out:

https://github.com/potocpav/xi_glium

**Comment by tnguyen14** [comment]
@leavengood I'm really eager to upgrade. However, I'm using a company provided Mac and they don't allow it yet. I'll check out xi_glium.
