### ISSUE TITLE
Selections break ligatures

### ISSUE THREAD

**Issue by porglezomp** [google/xi-editor#114]
When I switched to Zapfino while I was working on #113, I noticed that if one character of a ligature is selected then the characters are instead rendered with their individual glyphs.
<img width="404" alt="screen shot 2016-08-06 at 6 47 26 pm" src="https://cloud.githubusercontent.com/assets/1690225/17459446/60b3e692-5c06-11e6-88da-c55a34c84b1e.png">
(A demo with the _very_ visible Zapfino "ft" ligature.)

**Comment by raphlinus** [comment]
Yup. This is an underlying issue in Core Text - I just set a background color span, and that causes ligatures to be broken.

Ultimately, the solution is to draw all the backgrounds separately (not using background color spans in [NSAttributedString](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSAttributedString_Class/), then draw the text. This would solve other problems as well, including clipping of text by the background color span of the next line overpainting it. One "gotcha" is that drawing backgrounds correctly in the presence of [BiDi](https://en.wikipedia.org/wiki/Bi-directional_text) is _quite_ tricky. I think I'll have to do a first pass in which BiDi explicitly doesn't work, then a second pass to add BiDi.

**Comment by cmyr** [comment]
fixed in #164.
