### ISSUE TITLE
Does not build on Ubuntu OR build instructions are incomplete

### ISSUE THREAD

**Issue by hughbarney** [google/xi-editor#116]
$ pwd
/home/hugh/Dropbox/src/xi-editor
$ 
$ xcodebuild
xcodebuild: command not found

$ pwd
/home/hugh/Dropbox/src/xi-editor/rust
$ 
$ cargo build
No command 'cargo' found, did you mean:
 Command 'carto' from package 'node-carto' (universe)
cargo: command not found
$

**Comment by UnguidedFreedom** [comment]
The build instructions are actually quite clear. They state that XCode is needed and that XCode is only available for Mac OS. So no Ubuntu build for now

**Comment by eyelash** [comment]
The rust code builds quite fine on Ubuntu but you have to install cargo (`sudo apt install cargo` on 16.04 and newer or download from www.rust-lang.org).

**Comment by raphlinus** [comment]
Closing stale issue, thanks @eyelash for updating.
