### ISSUE TITLE
Add TUI for people who stuck with VT100 (like me)

### ISSUE THREAD

**Issue by hauleth** [google/xi-editor#117]
It would be nice to have some TUI interface which should be no harder than GUI.

**Comment by nikomatsakis** [comment]
Yes!

**Comment by little-dude** [comment]
I started to play with termion https://github.com/little-dude/xi-tui
I'm a complete beginner with both rust and TUIs, so it's more a learning project.
The json rpc module is taken from https://github.com/potocpav/xi_glium/blob/master/src/core.rs

**Comment by little-dude** [comment]
Hi,

I made some progress with [xi tui](https://github.com/little-dude/xi-tui), if you want to check it ouy. You can now do some basic editing. There are two main issues for now:

### Line wrapping

I have no idea how to do line wrapping. As far as I know the backend does not do it, so I assume it's the frontend job.

### Characters that are more than 1 column large

The backend updates come with a `scroll_to` value that gives the position of the cursor in terms of _characters_, but there are cases where characters are not exactly one column large.

- for tabs, I just assume the tabs are 4 spaces
- for alphabets with such characters, I'm planning to use [unicode-width](https://crates.io/crates/unicode-width). I have [an untested PR](https://github.com/little-dude/xi-tui/pull/1/files) for this.

**Comment by cmyr** [comment]
Frontends are now listed in the readme; that list includes several TUIs
