### ISSUE TITLE
Roadmap Issue

### ISSUE THREAD

**Issue by pradyunsg** [google/xi-editor#134]
Could you (or someone) create some sort of a road-map issue, which would provide like an overview of where this project is headed?

Something like twbs/bootstrap#17021 (except as an issue).

**Comment by pradyunsg** [comment]
Bump.

**Comment by emoon** [comment]
I think this would be great as well. Doesn't need to be super details but a rough idea is always interesting.

**Comment by cmyr** [comment]
tentative roadmap issue: #252
