### ISSUE TITLE
Modal?

### ISSUE THREAD

**Issue by brcolow** [google/xi-editor#14]
Sorry for the noise, but I was wondering if the xi-editor is going to be a modal text editor (a la vim) or a non-modal editor (a la emacs)? Or will the back-end (core) be (somehow?) mode-agnostic.

Thanks!

**Comment by raphlinus** [comment]
Right now it's non-modal. I'm envisioning also having a vim-compatible personality because some people prefer it and it's more efficient in some use cases.

Figuring out the details of this is not trivial. See #12 for a bit of discussion.

**Comment by JikkuJose** [comment]
👍 Hope there will be support..

**Comment by gnzlbg** [comment]
I like how spacemacs allow switching between modal and non-modal "meta-modes".

**Comment by raphlinus** [comment]
Closing this issue, choosing #93 as the master tracking issue. Still interested in doing it!
