### ISSUE TITLE
Split into xi-core and OS X frontend

### ISSUE THREAD

**Issue by theduke** [google/xi-editor#141]
Since there are multiple frontends popping up, and the goal is a independent structure,
I think it would make sense to split into a xi-core repo with the server and a separate xi-cocoa project for the frontend.

**Comment by Eh2406** [comment]
Could there be a list of frontends somewhere?

**Comment by raphlinus** [comment]
I have the repository created, just need to do the split.

**Comment by theduke** [comment]
How's that coming along, @raphlinus ?

While there are relatively few issues at the moment, it's confusing to separate what's related to the core vs the Cocoa frontend.
