### ISSUE TITLE
Linux Frontend

### ISSUE THREAD

**Issue by jcf** [google/xi-editor#142]
Hello all,

I'm interested in working on a Linux frontend, and wondered if there was already an effort underway.

If not, is there a strong concensus on the best UI kit to use? I was particularly interested in investigating [Rust GTK](https://github.com/gtk-rs/gtk) because being able to use Rust everywhere really appeals to me.

I'll most likely create a new repo and spike something out over the Christmas break, and would appreciate input/help from anyone else who's interested!

**Comment by AljoschaMeyer** [comment]
Here are some frontends you could look at:
- [gtk in vala](https://github.com/google/xi-editor/issues/92)
- [glium](https://github.com/potocpav/xi_glium)
- [terminal](https://github.com/little-dude/xi-tui)

Related frontend discussions:
- [web technologies](https://github.com/google/xi-editor/issues/140)
- [terminal](https://github.com/google/xi-editor/issues/117)
- [gtk+](https://github.com/google/xi-editor/issues/92)
- [libui](https://github.com/google/xi-editor/issues/84)

**Comment by mrandri19** [comment]
I tried to create a simple frontend with gtk-rs, but got stuck fighting with the borrow checker. I couldn't understand how gtk-rs cloning worked. Here's the repo anywayhttps://github.com/mrandri19/xi-gtk

**Comment by eyelash** [comment]
The reason that I'm using Vala instead of Rust for my [GTK front-end](https://github.com/eyelash/xi-gtk) is because the gtk-rs APIs are not stable yet and there were things I could not figure out how to do (creating a custom Gtk.DrawingArea that implements Gtk.Scrollable for example).
Besides that I think that Vala still feels a lot more native to GTK/GLib/GObject (kind of like the official macOS front-end is also written in Swift and not in Rust).

**Comment by jcf** [comment]
Thanks for the info, all! Very helpful. I'll definitely take a look at the repos you linked.

I have a bit of a Rust itch I want to scratch, which is what made me think of gtk-rs. As a relative newbie, it sounds like getting my feet wet in such a young area may not be the best option for my first significant foray into the language.

I wonder, is there a Wiki page or maybe something we could add to the project README so others can find what's been shared above?

**Comment by est31** [comment]
One of the goals of the xi editor seem to be to use the native gui toolkit of the current platform. On linux though there is no such thing, its split between the GIMP toolkit and Qt.

**Comment by alexanderadam** [comment]
Besides the frontends Aljoscha mentioned, there is also [gxi (GTK)](https://github.com/bvinc/gxi)

@est31 especially for editors it usually doesn't matter which UI kit is used. See, sublime text became popular although a custom toolkit was used.
Usually licensing and/or personal taste are more important.

**Comment by UnicodeAlt255** [comment]
I thought QT was preferred these days?

**Comment by jansol** [comment]
Closing this as there are multiple linux-compatible frontends listed in the readme now.
