### ISSUE TITLE
undo is broken

### ISSUE THREAD

**Issue by eyelash** [google/xi-editor#143]
**test case:**
- open Xi
- type a few letters
- activate Edit > Undo or hit ⌘Z

**expected result:**
- the letters are removed again

**actual result:**
- nothing happens

**Comment by raphlinus** [comment]
Doesn't repro for me. I wouldn't be surprised if there were something going on, but I can't see it.

**Comment by eyelash** [comment]
hmm... I did a clean build on Xcode 8.2.1 on macOS 10.11.6 with the latest Rust.
Also I tried to implement undo for xi-gtk on Linux and it never worked.

**Comment by adrientetar** [comment]
Undo doesn't work indeed. xi-core dumps `got update notification Undo` on stderr but nothing comes out of it.

**Comment by raphlinus** [comment]
I'm able to repro in release build, but not in debug. Odd. In any case, this is obviously a real issue.

**Comment by eyelash** [comment]
It looks like the [insert inside the debug_assert](https://github.com/google/xi-editor/blob/1a50e29f546cd4a2053a362a13f7dd5182431156/rust/core-lib/src/editor.rs#L663) is to blame here.

**Comment by raphlinus** [comment]
@eyelash Thanks for tracking that down! It was on my list of things to look into, but I didn't get around to it yet.
