### ISSUE TITLE
Migrate Swift code to 3.0

### ISSUE THREAD

**Issue by raphlinus** [google/xi-editor#144]
Xcode 8.2 gives a warning that Swift 2.3 is deprecated. Using the conversion tool still leaves 31 errors. Most are "Contextual type 'AnyObject' cannot be used with dictionary literal", which is easily fixable by adding `as AnyObject` after the literal. The NSData for the receive buffer must be replaced with Data.

Part of the reason I'm posting this as an issue is to get feedback on when this should be done. I'm happy chugging along with 2.3 for now, but at some point it needs to change. It also obviously can cause merge conflicts for PR's in flight.

**Comment by adamhammes** [comment]
I think it would be appropriate to bump the version now. There are only 4 open PRs currently, two of which have no code changes.

**Comment by AquaGeek** [comment]
I'd push to do this sooner rather than later. Xcode 8.2 is the [last version that will support Swift 2.3](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html).

**Comment by rkusa** [comment]
The only affected PR seems to be #136, which needs to be touched (copyright header added, merge conflicts) anyway. So I'd agree that now would be a good time.
