### ISSUE TITLE
More text commands

### ISSUE THREAD

**Issue by adrientetar** [google/xi-editor#150]
- canUndo()/canRedo() is needed to show/hide the UI elements; I believe this should be implemented in the  core as trying to track that in the frontend would be hacky at best (e.g. how to record clean state?)
- a "scroll_to" command to send a target cursor position is afaict required to implement a "Goto" command
- auto indent would be nice, I guess that would be a separate plugin
- find/replace

**Comment by raphlinus** [comment]
All these are good. For auto indent, I absolutely plan for this behavior to be in the plugin; that means exposing more editing abilities to the plugin. I'm starting to play with a Rust-specific plugin (that just does the lexing by hand, _not_ using regexes like syntect).

For find, I'm thinking of implementing a non-performant version of the algorithm first, then refining it later. A highly performant version would need to handle:

* the non-contiguous string representation (so can't just use existing libraries)
* Unicode case folding
* incremental operation as a background task so it can be interrupted, etc

Agreed that canUndo / canRedo needs to be supported in the core, the front-end doesn't have quite enough state. I looked at this on Mac, and found that many apps don't bother graying out the menu for these, so didn't prioritize it.

**Comment by jansol** [comment]
Closing as all points mentioned are either implemented, being implemented and/or have their respective tracking issues.
