### ISSUE TITLE
selection can clip neighbouring lines [macOS]

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#163]
I saw this mentioned in #114 but didn't see an issue for it:

In some circumstances the background color of a selection can clip another line. As far as I can tell, I've only seen this when the text in the selected line is bold? 

![screen shot 2017-02-27 at 2 24 55 pm](https://cloud.githubusercontent.com/assets/3330916/23376038/a77bc688-fcf8-11e6-9402-ba34e2e44b66.png)

**Comment by raphlinus** [comment]
The solution to this is to paint all the background color spans first, then paint the text over it. Probably the reason why bold is affected more is that metrics in the font indicate a large ascent, which would make the background rectangle taller.
