### ISSUE TITLE
Cmd-T should open a new tab

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#168]
How to go about programatically adding a new tab through the NSDocument model isn't totally clear to me, but there are some clues in the [AppKit 10.12 release notes](https://developer.apple.com/library/content/releasenotes/AppKit/RN-AppKit/#10_12Window%20Tabbing); if that doesn't make this clear then there was a talk at WWDC this year that was probably relevant: [Crafting Modern Cocoa Apps](https://developer.apple.com/videos/play/wwdc2016/239/).

**Comment by raphlinus** [comment]
An alternative is just to set tabbing mode to preferred. I believe the code is as simple as `windowController.window?.tabbingMode = .preferred`. Personally I would find this behavior appealing - if I want a new window, not a tab, I'm fine with tearing it away. I mentioned this possibility in #57.

Sort of the opposite problem, but when we open a file and the current tab is empty, can we have the file replace the current tab? I had this implemented but it seems to be gone now.
