### ISSUE TITLE
Warn on close with unsaved changes

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#174]
This is discussed a bit more here: https://github.com/google/xi-editor/pull/172#issuecomment-283775673 but regardless of implementation details, this is a glaring hole in the UI at the moment. Related to #173, we could also show save status in the status bar.

**Comment by cmyr** [comment]
@raphlinus played around with this a bit by adding a new command in the backend, but I'm not sure how to determine wether or not the buffer has unsaved changes. I would expect `Editor.text_dirty` to be what I'm looking for, but afaict it only reflects whether the Rope contains _any_ text. It also doesn't seem to track undo state. Am I missing anything?

**Comment by raphlinus** [comment]
Yeah, thinking about this, tracking whether the buffer contains unsaved changes is something the core needs to track. It's actually pretty nontrivial, as edits can come from a variety of sources (including plugins), each of which has potentially different undo state. I think the right way to do this is to have a method in the CRDT engine which tells you whether two revisions are the same (ie the set of deleted characters relative to the union_str are the same). Then that should get reported to the front-end as a boolean "dirty" (maybe I'll just add that to the update method).

**Comment by cmyr** [comment]
my feeling here (as well as with the the word segmentation) is that a quick implementation with a good API is a very acceptable stop gab. I think some heuristic ASCII wordbreak algo is a very reasonable place to start, and then better unicode support can be swapped in further down the list. 

I was implementing this as a blocking 'debug_info' edit method, (edit because it's always directed to a given tab, although it does feel like it should maybe be more like 'new_tab') which I imagine could also be used to return things like word/byte/line counts and other metadata. Although I guess then you wouldn't want it blocking. Anyway, my thought was just to throw this call out when you're notified of a user close action, and then act appropriately based on that info.

**Comment by cbrewster** [comment]
I am looking into working on this. I am still very new to this codebase so my understanding of how Revisions work may be off. To compare two revisions `a` and `b` to determine if they are the same, can I just directly compare their `from_union` subset? Or do I need to look at all the edits between `a` and `b` and see if there is a net gain of zero?

**Comment by raphlinus** [comment]
@cbrewster Actually that's an interesting question.

Short answer, I think revision equality based on `from_union` is useful and would support using it. That said, there are other choices.

To understand the subtle distinctions, consider an initially empty buffer, followed by "A" then backspace. The initial and final revisions have the same from_union subset (indicating that the "A" is deleted).

Most editors that I've tested use a stricter notion of equality, so "A" backspace would not be considered equal to initial. On the other hand, "A" undo would be. In xi, this notion of equality would be represented by comparing the set of undo groups. After "A" backspace, there are two undo groups in a "done" state: the insertion and the deletion.

I personally like the first. I think it usefully indicates whether saving the buffer will have any effect. It's fairly common to accidentally type into a buffer.

In both cases, when the pristine revision drops off the end of the undo queue, then it should be considered impossible to reach it (as a consequence, after an extended sequence of "A"+backspace pairs  it would not be possible to return to a pristine state).

A looser notion of equality is simply the buffer contents, so from an initial value of "A", backspace+"A" would also be considered equal. But I don't know of any editor that does this, and I don't think we should.

Best of luck implementing this and let me know if you have any questions.

**Comment by cbrewster** [comment]
How should I go about sending the unsaved/saved state to the frontend? Should it be grouped in with the normal update or should it be separate? If we do group it with the current update, we have to send an update after the save completes to update the frontend that the save was completed.

**Comment by raphlinus** [comment]
Should be grouped with the update. There a few things that need to be added there, including line numbers (#184). Sending an update after save completes sounds right to me (it is a change to visible state).

**Comment by cbrewster** [comment]
Should the update sent after a save send any lines?

**Comment by raphlinus** [comment]
No. But you shouldn't have to generate it manually, it should be enough to let the dirty logic handle it. _Today_ that's going to resend content, but that will be fixed.

**Comment by eyelash** [comment]
> A looser notion of equality is simply the buffer contents, so from an initial value of "A", backspace+"A" would also be considered equal. But I don't know of any editor that does this, and I don't think we should.

Atom does this and I really like it. I think we should try to find the best solution for every problem instead of just doing things a certain way just because most editors do it that way and unsaved changes indication based on buffer equality makes a lot more sense to me than anything else.

**Comment by cmyr** [comment]
@cbrewster if you feel like you're ready for client integration I can put together a branch with statusbar support this morning. I have it mostly implemented and I have a good idea of what is left to do; it's a bit particular because we want to support having plugins add & update status bar items. In the meantime I'd implement in core and just log changes in the client.

I agree with @eyelash here as well: I don't think existing editor behaviour is the best rubric, here. The ground truth of "changedness" to a document should be whether or not the bytes in the buffer are the same as the bytes on disk. I think the behaviour of a lot of editors is a product of their implementation details, e.g. they're often using data structures where using the undo stack as a proxy for dirtiness is their best option. It seems to me like this is a place where persistent ropes give us the opportunity to do better?

**Comment by raphlinus** [comment]
Efficient equality testing for ropes is a great starter project for someone who wants to dive into the rope code. High level overview, if lengths mismatch or there's pointer equality, you're done. Otherwise, recurse and iterate through both sets of children, maintaining an offset. Compare the shorter child (the one ending first) with the corresponding substring of the other. If you're at leaves, compare bytes. It's not trivial; among other things, the trees may be different height.

For added fun, make an equality trait for generic ropes, not just strings. I think this would need a fun "compare with slice" trait to avoid doing allocations for the subsequence operation.

I'm also happy to improve on existing editor behavior; I just want to understand it first (Chesterton's fence).

**Comment by cmyr** [comment]
this is closed by #203
