### ISSUE TITLE
update to serde 0.9

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#182]
serde 0.9 introduces the nice `json!` macro, which gets rid of the awkward `ObjectBuilder` stuff. It also provides `#[derive(Serialize, Deserialize)]`, which might be helpful at some point.

I'm opening this issue because I'm going to start this conversion, and wanted to give @raphlinus the opportunity to interrupt me if there's some good reason to hold off.

**Comment by raphlinus** [comment]
Upgrading to 0.9 sounds great. The only potential issue (which may affect use of Serialize and Deserialize traits, and relevant macros) is that eventually json may become optional, as Fuchsia front-ends may drive the editor entirely through [fidl](https://fuchsia.googlesource.com/fidl/). So it's important not to put unremovable dependencies in.

**Comment by cmyr** [comment]
@raphlinus I'm a little confused by the comment here: https://github.com/google/xi-editor/blob/master/rust/core-lib/src/view.rs#L107

This bit of code looks like the part that will require the most work with moving away from `ObjectBuilder` and `ArrayBuilder`, and I would avoid doing that work if this wasn't actually in use. It sure _looks_ like it's used, though: it gets called from `do_render_lines` in the editor.

**Comment by raphlinus** [comment]
Yup, `render_lines` should be removed from the front-end / back-end protocol. It's replaced by `request_lines` (which is async), and, in fact, with the recent scrolling changes, it's entirely optional as long as the front-end keeps the core updated with respect to its scroll range.
