### ISSUE TITLE
xi-editor will be an ide？

### ISSUE THREAD

**Issue by NateLing** [google/xi-editor#187]
an plan to make it be an ide?

offer language service,build system and so on

**Comment by cmyr** [comment]
There is no plan to have xi _be_ an IDE, but much IDE-like functionality (including a build system and support for the language server protocol) should be possible through the plugin system.

**Comment by thomas-profitt** [comment]
Just as well, a Xi editor could be included _in_ an IDE. I imagine, in the future, multiple IDEs could implement frontends with the Xi core, compatible with plugins. Xi could be flexible and efficient enough to be something of a standard.

**Comment by NateLing** [comment]
@thomas-profitt @cmyr  well, i'm developing an golang IDE. i will wait for xi-core. so i could do it base on XI.
