### ISSUE TITLE
modify RPC protocol to support better lifecycles + multiple views

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#191]
## Summary

The current way documents are created, opened, and closed does not cleanly support integration with plugins, or future support for multiple views (which should be at least considered while developing the plugin system). This is true in two particular ways: first that the RPC protocol isn't adequately descriptive to allow for cleanly determining buffer/view lifecycles, and second that there is currently a strong coupling between a buffer and a view (one buffer, one view) that does not reflect the ultimate goals of the protocol; and it would be helpful to reconsider this now, because it will allow for a better understanding of how plugins should work. I will address these two points in turn.

### Lifecycle

I discussed this briefly in #186, but I want to take a more holistic approach.

Currently, when the client creates a new window, it sends the `new_tab` RPC to the core. The core then picks a tab name (incrementing an internal counter) creates a new `Editor` instance, a new `TabCtx` instance (basically a collection of references to shared resources like the client, the kill_ring, the stylemap, etc) and then returns the tab name to the client. 

This occurs regardless of why the window was created; the same process occurs for opening a window as for creating a new one. (I outline this pretty well in #186, I won't repeat myself here.)

When the client closes a window, the `Editor` receives no notification; the core simply removes its reference to the editor, and the memory is cleaned up when it goes out of scope.

It is feasible that an eventual plugin API will want to include lifecycle events such as `will_open_file`, `did_open_file`, `new_file`, `will_close_file`, and `did_close_file`. It is feasible that a new buffer might be created, _with a path_. (E.g, in vim: `:e ~/i_dont_exist_yet.txt`).

Semantically, there is no such thing as a view which is not backed by a buffer. If the client is creating a view, it is for either a new buffer, to load a file, or to create a new view into an existing buffer. This should be reflected by the protocol. 

A possible solution: replace `new_tab` with `new_buffer`, and add `open_file`. `open_file` (or some other name) could eventually be overloaded to handle opening new views into an open buffer, or (probably better) there could be a `clone` or `new_view` RPC. `open_file` would be a command at the top level (a `TabCommand`) alongside `new_tab`/`new_buffer` and `delete_tab`. 

Alternatively, there could be a single `new_view` RPC that handled all three cases, through a few params. (After more thinking I'm leaning in this direction: `new_view` + a `path` param; `close_view`, which closes a view; a buffer is closed when it has no views).

#### An aside, on naming:
Something I found difficult when I was first starting to familiarize myself with the codebase was some of the naming conventions. Naming is hard, but I think in particular the use the term `tab` in the backend & the RPC protocol is confusing, and I think it might belay a certain underlying ambiguity. I appreciate that the name `view` is taken. A 'tab' (in the backend) is essentially a buffer + a view. How does this scale to multiple views? Each view needs an identifier, for dispatching view specific events, like cursor motion. Do buffers need explicit identifiers? Probably. A buffer open in multiple views should share an `Editor` instance, but a new view might be created by selecting an already-open file from File>Open, in which case the core would need to have a hashmap or something of buffer identifiers (or filenames) to `Editor` instances.

So there isn't a 1-to-1 relationship between `Editor`s and (client) views, but there _is_ between client views and core `view` instances. So I wonder if `view` might not be a better word than `tab` to describe this concept after all.

### Decoupling views and buffers

The second change I would like to propose is a decoupling, in the protocol and the internal API, between views and buffers. This does not entail actually _implementing_ multiple views, but merely adopting the API & RPC protocol that will be necessary when we do. 

#### What would multiple view support look like?

Currently an `Editor` instance owns a single view. To support multiple views, either an `Editor` will have to have references to multiple views (and be passed in a view identifier with an action) or else something 'higher up' will keep track of which editors are associated with which views, and pass in a reference to a view alongside a given action. The first might be easier to implement, and the second feels conceptually purer. I'd need to dig in a bit more to see if I have a strong opinion about this.

(Maybe the first _does_ make more sense: even when receiving an event from one view, the editor will potentially need to send updates to any others).

## Conclusion

I've more or less talked myself into this, and maybe also started to think that multiple views will actually be easier to implement then I'd thought.

Unless @raphlinus has strong feelings here, I'm going to start working on this: I consider it a blocker on plugin process, and it's also a nice self-contained piece of work that can be done in isolation from other changes.

**Comment by rkusa** [comment]
The term`buffer` refers to `TabCtx` in the current implementation, right?

**Comment by raphlinus** [comment]
@rkusa It really means `Editor`, as that's where the state is for the document itself. The `TabCtx` is an ephemeral struct containing information needed to process a single request from the front-end.

**Comment by cmyr** [comment]
Yea, I should clarify my terms. When I talk about a `buffer` I'm talking about the underlying storage for a saved or unsaved file that is being edited. In effect this basically means an `Editor` instance (there should always be a 1-to-1 relationship between an editor and a buffer).

**Comment by rkusa** [comment]
Thanks for clarification!

**Comment by eyelash** [comment]
One use case I'd like to see covered by the protocol is restoring a previous session on start up. Right now this is not possible because opening a file is always initiated by the front-end whereas for session restoring it would need to be initiated by the core.

**Comment by cmyr** [comment]
@eyelash That's a good point. My initial thinking was that the backend only ever had to have the concept of a "view", and the actual layout and display of that view would always be the frontend's responsibility (this could vary based on platform capacity & idiom, e.g. an iPad or a TUI can only have a single window, etc). 

But thinking about plugins, there's definitely cases where a plugin wants to explicitly open a new window and maybe set splits, e.g. for displaying a diff.

For state restoration, my immediate thought is that responsibility could be split: the frontend should stash window/tab/split information plus view identifiers, and the backend should stash view identifiers plus document state; on relaunch the frontend restores window state and then requests a restore with some session identifier, and then each client view is reattached to the relevant core view.

It's an open question of whether, say, the core should ever be aware that a particular view is in a particular window, and that window's dimensions, etcetera. I think if the answer is 'yes', it's 'yes, but behind a pretty thick layer of abstraction'? E.g. the API should allow a degree of flexibility on the client side in terms of implementation.

**Comment by cmyr** [comment]
closes with #194
