### ISSUE TITLE
Text selection is always a step behind

### ISSUE THREAD

**Issue by cbrewster** [google/xi-editor#195]
While selecting text on the frontend I noticed that it seems like selection is a step behind. 
For example, let say I have `def` selected while still holding down the mouse.
```
abc|def|g
```
If I drag over the g, the selection state remains the same, but then if I drag back over the f the selection state goes to:
```
abc|defg|
```
This was the correct state for when I moved the mouse over g, but not correct for the current expected state. Same issue when selecting across rows as well.

**Comment by cmyr** [comment]
@cbrewster want to check a few recent builds and see if this is a regression?

**Comment by raphlinus** [comment]
I have a fix; basically it's sending last rather than the current position to the drag method.
