### ISSUE TITLE
Request: Compatibility with Plasma 4

### ISSUE THREAD

**Issue by Bluebird45** [google/xi-editor#22]
Hi,

I hope it's alright to post a feature request here. It seems a good time to post this since there is yet to be a Linux front-end.

My default distro, Debian stable (Jessie) with KDE desktop, currently runs the Plasma 4 desktop environment. Other Debian-family distros, notably Ubuntu, have already upgraded to Plasma 5.

In Sublime Text 3, the designers [evidently](https://forum.sublimetext.com/t/browse-packages-no-window-appears/15461/3) made the decision to make it dependent on Plasma 5. As a result I find that some of the menus don't work, and there is the occasional bug of unknown cause that makes me wonder if it is due to the dependency on Plasma 5.

The testing version of Debian has Plasma 5 but it has too many annoyances for me to get on with my work. I'd rather wait until the next stable version comes out next year. 

I note that one of your design goals is beauty, and so you might decide to standardize on Plasma 5. I request that whatever Linux front-end is produced be compatible with Plasma 4.

EDIT: I see that there is a project, [xi-glium](https://github.com/potocpav/xi_glium), started since yesterday, and I'm playing with that right now. It is fast and clean and has vast scope for being added to.

**Comment by jansol** [comment]
Seems off-topic for xi core. I suggest opening issues in relevant frontend repos. Namely [xi-qt](https://github.com/sw5cc/xi-qt), [gxi](https://github.com/bvinc/gxi), [xi-gtk](https://github.com/eyelash/xi-gtk), maybe even [xi-electron](https://github.com/acheronfail/xi-electron).
