### ISSUE TITLE
simple find / replace

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#224]
~This should be case insensitive & unicode aware. It should be reasonably performant when dealing with ASCII.~

Reusing this issue as a tracking issue for shipping actual functioning find & replace. This is very close, thanks to @raphlinus and @rkusa. Current status:

- as of #226, basic case insensitive search now exists in xi-core.
- with of #286 (WIP), we have rpc methods wired up for find next / find prev.

next steps:
- [ ] basic UI for find/replace in xi-mac. This should support find next / find prev, replace current, replace all.
- [ ] implement replace RPC. This should act on the current selection.

It may make sense to just implement find UI first, and treat replace as a separate work item.

**Comment by scholtzan** [comment]
This can also be closed now :D
