### ISSUE TITLE
crash on `MoveToBeginningOfParagraph` event

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#228]
This came up while testing https://github.com/google/xi-mac/pull/28. I assumed it was a result of either 388174e or 7614924 but I played around quite a bit and apparently it's older.

Easy to reproduce: open a new document, select-all, and fire `move_to_begnning_of_paragraph`. (ctrl+A in xi-mac). 

The crash is a subtraction overflow in `Editor::cursor_start`, where view.sel_min() is 0 and the cursor_col is > 0. 

A quick fix would be to just use `checked_sub`, but I'd want to look at underlying behaviour first. I'll get around to this if nobody beats me to it. 

@rkusa if you're up soon and looking for a bite-sized one this might be fun?

I'm starting to warm up to more aggressive testing.

**Comment by rkusa** [comment]
I am almost done with another PR, and I am happy to look at this afterwards! 👍

**Comment by cmyr** [comment]
@rkusa sorry I beat you to it 😢 #229

**Comment by rkusa** [comment]
@cmyr 😄 No problem, it is good to see it solved!
