### ISSUE TITLE
Build error: custom derive attribute panicked

### ISSUE THREAD

**Issue by VectXi** [google/xi-editor#233]
▶ cargo build --verbose
       Fresh xi-unicode v0.1.0 (file:///Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/unicode)
       Fresh serde v0.9.12
       Fresh bytecount v0.1.6
       Fresh libc v0.2.21
       Fresh itoa v0.3.1
       Fresh quote v0.3.15
       Fresh xi-rope v0.2.0 (file:///Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/rope)
       Fresh time v0.1.36
       Fresh dtoa v0.4.1
       Fresh unicode-xid v0.0.4
       Fresh crossbeam v0.2.10
       Fresh num-traits v0.1.37
       Fresh synom v0.11.3
       Fresh serde_json v0.9.9
       Fresh syn v0.11.10
       Fresh xi-rpc v0.2.0 (file:///Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/rpc)
       Fresh serde_codegen_internals v0.14.2
       Fresh serde_derive v0.9.14
   Compiling xi-core-lib v0.2.0 (file:///Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/core-lib)
     Running `rustc --crate-name xi_core_lib core-lib/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b3ae71f7a1704f17 -C extra-filename=-b3ae71f7a1704f17 --out-dir /Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps -L dependency=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps --extern serde_derive=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libserde_derive-dc77615547da0921.dylib --extern xi_unicode=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libxi_unicode-d66e836bb309c764.rlib --extern xi_rpc=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libxi_rpc-d38e36fda454b2f0.rlib --extern serde=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libserde-83807b4f9801fcb4.rlib --extern serde_json=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libserde_json-523da6ef63875c40.rlib --extern xi_rope=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libxi_rope-da214fa59a28ef2a.rlib --extern time=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libtime-cd5e3a346d1a17b6.rlib`
error: custom derive attribute panicked
  --> core-lib/src/run_plugin.rs:39:10
   |
39 | #[derive(Serialize, Deserialize, Debug)]
   |          ^^^^^^^^^
   |
   = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `xi-core-lib`.

Caused by:
  process didn't exit successfully: `rustc --crate-name xi_core_lib core-lib/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b3ae71f7a1704f17 -C extra-filename=-b3ae71f7a1704f17 --out-dir /Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps -L dependency=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps --extern serde_derive=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libserde_derive-dc77615547da0921.dylib --extern xi_unicode=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libxi_unicode-d66e836bb309c764.rlib --extern xi_rpc=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libxi_rpc-d38e36fda454b2f0.rlib --extern serde=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libserde-83807b4f9801fcb4.rlib --extern serde_json=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libserde_json-523da6ef63875c40.rlib --extern xi_rope=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libxi_rope-da214fa59a28ef2a.rlib --extern time=/Users/xishengquan/Documents/src/vect/xi-mac/xi-editor/rust/target/debug/deps/libtime-cd5e3a346d1a17b6.rlib` (exit code: 101)

**Comment by raphlinus** [comment]
The last time I saw this bug it's because the rustc was installed through homebrew. A version installed from rustup worked better.

**Comment by VectXi** [comment]
@raphlinus Thank you, you are right.
