### ISSUE TITLE
Compile error in xi-core-lib v0.2.0

### ISSUE THREAD

**Issue by todolson** [google/xi-editor#247]
I'm getting the following error compiling the most current commit (2017-05-01, 51c484b) of xi-editor:
```
   Compiling xi-core-lib v0.2.0 (file:///Users/tod/src/xi-mac/xi-editor/rust/core-lib)
error: proc-macro derive panicked
  --> core-lib/src/run_plugin.rs:39:21
   |
39 | #[derive(Serialize, Deserialize, Debug)]
   |                     ^^^^^^^^^^^
   |
   = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `xi-core-lib`.
```

Mac OS X version 10.11.6
rust version 1.17.0 (installed via homebrew)

**Comment by raphlinus** [comment]
This appears to be a consistent problem with rust installed with homebrew. People who use rustup find that it fixes it for them.

https://github.com/rust-lang/rust/issues/39870 appears to be the actual issue. Looks like it's in the process of getting fixed, just hasn't made it to your install yet?

**Comment by todolson** [comment]
Yes, that ticket seems to still be in process. Too bad, Homebrew usually works very well for me.

Meanwhile, I can compile successfully with rustup. Thanks for pointing that out.

**Comment by ilovezfs** [comment]
This should no longer be a problem in Homebrew due to https://github.com/Homebrew/homebrew-core/pull/14490.
