### ISSUE TITLE
Editor sometimes crashes when pressing down key

### ISSUE THREAD

**Issue by shssoichiro** [google/xi-editor#25]
I'm having trouble tracking down exactly what triggers this, but if I type a few lines into the editor, then hit up and down keys, I sometimes after hitting the down key get a crash with this error:

```
thread '<main>' panicked at 'to_base_units called with arg too large', rope/src/rope.rs:162
```

This is on OS X 10.11 with latest Rust nightly.

**Comment by njaremko** [comment]
Seeing as how nightly is unstable...have you tested this issue with Rust 1.8?

**Comment by raphlinus** [comment]
This is _probably_ the fg color spans stuff, which just went in. I'll take a closer look. Very unlikely a compiler issue.

**Comment by potocpav** [comment]
It was happening in xi_glium at least since f2a567b (nightly Rust).

Reproduce: Make a file with the last line not blank, place cursor at the beginning of the file, use down arrow to go all the way down.

**Comment by leavengood** [comment]
Maybe an end of file bug and/or related to a trailing newline (or lack thereof.)

**Comment by shssoichiro** [comment]
I did have it crash once when moving from line 2 to line 3 of a ~6 line file, so it's not always at the end of the file. Hence why I'm having such a difficult time consistently reproducing.
