### ISSUE TITLE
Refactor Engine

### ISSUE THREAD

**Issue by trishume** [google/xi-editor#256]
Possible refactorings below. These were written down while reading the Xi code, I don't necessarily know if these are a good idea yet. I'm writing them down now more to document what confused me in the hopes that we can make it less confusing to new readers.

- [ ] Should `Subset` conceptually represent a set of the ranges (i.e the current `dels` field) or the complement of it. This effects method names and documentation. For example maybe `is_trivial` should be named `is_empty` and `add_deletion` should be `add_range`. This may make it make more sense when representing insertions and deletions in revisions.
- [ ] Have a separate tuple-struct wrapper of `Subset` called `Transform` that conceptually represents the corresponding function. Would use function terminology like `compose` and `apply`. Would make it hard to mix up which `Subset`s represent deletion/insertion ranges and which represent coordinate transforms.
- [ ] Refactor method names on `Subset` in terms of Git terminology. This one may be dumb but it's a commonly known way of thinking of revision graphs. For example `transform_expand` seems analogous to `rebase` or `cherry-pick`.
- [x] `DeltaElement::Copy` needs a doc comment explaining exactly what it is copying from, and how the whole `Delta` representation works. I now think I understand that the `Vec` represents the entire document, which some segments copied from the previous `Rope` and some new nodes inserted. Deletions are represented by the gaps between `Copy` elements.
- [ ] Add checking for coordinate space transforms. This might be getting a little too extreme: Do the previously-mentioned `Transform` wrapper for `Subset`, then add fields for the from and to revision of the coordinate transform. Add a `checked_apply` function or parameters to the normal apply function that checks that the apply function is transforming the right coordinates. If this was Idris I'd do this all with type level revision numbers and check it at compile time, but this is the next best thing. I'm not sure how helpful it would actually be though.
- [x] [Doc comment for `transform_expand`](https://github.com/google/xi-editor/blob/master/rust/rope/src/subset.rs#L148) needs parentheses. I interpreted "not in s1 or in s2" as "not (in s1 or in s2)", but it is actually "(not in s1) or in s2". One of those ambiguities in English that is resolved verbally through cadence and inflection, but is ambiguous in text. I read it in my head wrong and thus was confused.

@raphlinus: Is it just because I haven't finished reading or does the Engine double-account for deletion concept-naming-wise? The `Subset` type seems to be intended to conceptually represent the subset of the rope that is kept, as evidenced by names like `add_deletion` and `dels`. However then the `Edit` type has `deletions: Subset` and `inserts: Subset` and I'm pretty sure both of those are named as if the `Subset` is the set of deleted/inserted characters. Given the concept `Subset` represents, it seems that those should either be named `kept` and `not_inserted` respectively. I'm not even clear what the `Subset` under `inserted` contains, does its `dels` property contain the inserted ranges and thus it would be better named `not_inserted`, or does its `dels` property contain the ranges that were not inserted and the name is good.

**Comment by trishume** [comment]
Update: I now think I understand the operations on `Subset`. The doc comments didn't help much, but using a combination of them, the tests, and drawing things out on paper using a notation I invented I think I've got it. 

If I had a text editor on this computer I would submit a PR improving a bunch of the doc comments, but alas it is a Chromebook. I might try using the Github web interface to do it though.

I only managed to decipher the transforms by thinking of a Subset as a transformation deleting certain characters by identity that only works on a given base text. If Rust was dependently typed, the base text could be a type parameter. This seems to be the clearly correct way to think about it given our discussion yesterday but isn't obvious just from reading the code, I'd like to fix that and to re-phrase the doc comments on the transforms with that way of describing things.

I've attached a scan of the diagram and notation I used, in case it helps anybody else understand (cc @cmyr @rkusa in case you are interested). First section describes notation, second section is the operations on the `Subset` type, third section is a translation of the `transform_case` function from the `Subset` unit tests, and an example of string values that pass.
[Scan of my notes](https://github.com/google/xi-editor/files/980518/20170505155720528.pdf)

**Comment by cmyr** [comment]
I'm really happy to see someone digging into this stuff. I think anything that improves documentation and general clarity of use in engine.rs (and in the project more generally) is very welcome. I've only dipped in there as needed, so I don't have strong opinions about any of your particular suggestions, but as a whole I think they point in a very good direction.

I'm personally tickled by the idea of using the git terminology where appropriate. (I'm at your mercy in terms of knowing whether or not it's appropriate, though)

**Comment by raphlinus** [comment]
While we're scanning sketches, here's one from a while back that visualizes these `Subset` objects as regions in a 1D space. I'm not going to vouch for them 100% but as I recall, these diagrams were very helpful. One strangeness is that these represent the ranges that are retained, rather than the regions that are deleted, and I tend to favor the latter these days.

Proper documentation would be an _extremely_ useful artifact at this point, I think.
![scan 1](https://cloud.githubusercontent.com/assets/242367/25768024/f11d1068-31b3-11e7-97f8-fefec688c844.jpeg)

**Comment by trishume** [comment]
The fact that you used to think of things as ranges retained and switched to thinking of them as ranges deleted shows in the inconsistent naming in the code, which makes things very confusing.

There's two ways to fix the fact that everywhere `Engine` says `deletes` it contains a `Subset` that represents things that aren't deleted, and similarly for `inserts`:

1. Fix the names in `Engine`.
    - Rename `inserts` to `inverse_inserts`, `to_old_union` or `current_union_to_old`
    - Rename `deletes` to `kept`, or `kept_from_last`
1. Rename the methods on `Subset` so that they refer to the ranges it contains as the elements of the set and not the complement.
    - Rename `is_trivial` to `is_empty`
    - Rename the `dels` field to `ranges`
    - Rename `intersect` to `union`
    - Rename `apply(Rope)` and `apply_to_string` to `delete_elements_in(Rope)`
    - Rename `range_iter` to `complement_range_iter` and `_deletions` to `_ranges` or an iterator.
    - Rename `add_deletion` to `add_range` in `SubsetBuilder`
    - Rename `invert_insert` to `inserted_set`
1. Rename everything as if they are transform functions and not sets. I'm not sure exactly what this would look like but perhaps:
    - `Subset` would become `ShrinkTransform` or `DeleteDelta`
    - Rename all the `Subset` methods like in the other option.
    - maybe could add a wrapper `InsertDelta` so that `Delta.factor` returns `(InsertDelta,DeleteDelta)` and the methods of `Delta` that only work on insert-only deltas could be defined on `InsertDelta` with possibly a `Deref` impl for the others.
    - That leaves `invert_insert` returning a `DeleteDelta` which is reasonable, but unfortunately now `Edit` stores `inserts: DeleteDelta` which is weird, so we rename that to `inverse_inserts`. This actually makes sense in the context of how `inserts` is used in `transform_intersect` with `from_union`.

These all seem like plausibly reasonable paths. They're ordered by effort and one could argue also by niceness, but I'm not sure about the niceness part. Any thoughts on your favorite abstraction @raphlinus? 

<!--
My problem right now, and that probably just requires more reading and thinking, is that I understand why `inserts` and the code in `Engine` that uses it works, but I can only do so by thinking of the underlying `dels` ranges and what `transform_expand` does to them. I haven't yet fit `inserts` into my higher level abstracted model that doesn't require me to think about ranges shifting around.

The problem is in my current model (the one that I scanned a sketch for) a subset is a text transformer specialized for a given piece of text with a given set of deleted characters. I know that in my model the deletion set of `inserts` is actually the set of characters inserted, but I don't know what the base text is, and then the base is the union string after the insert is done. --!>

**Comment by raphlinus** [comment]
Totally agree that naming is inconsistent and should be cleaned up.

I'm inclined to rule out 3, because I think inverse transforms makes the terminology more confusing. There _is_ a 1-1 correspondence between sets and transforms, but to my mind the set representation is "more invariant" whether you're doing an expand or shrink transform.

Of the other choices, I'm not obviously seeing a clear choice. In the case where the same concept exists as in the JS code, I'm inclined to go with the latter, but coverage is far from complete.

**Comment by rkusa** [comment]
Thanks for the scanned documents! They will be handy the next time I'll do something at the Engine-level (because I am already feeling how I start loosing the understanding that I build when reading through this part of the code).

I remember being confused by`dels` when it was about deleted ranges. Other then that, I personally do not have a strong opinion on what the best name for a certain method is, but I am always pro towards consistency.
