### ISSUE TITLE
warn when the front-end sends a notification instead of a request

### ISSUE THREAD

**Issue by eyelash** [google/xi-editor#263]
When the front-end sends a notification but the core expects a request, the request will be processed but the response will be silently dropped.

[Relevant code](https://github.com/google/xi-editor/blob/1f610e23e38fc1311eefb9c4e8d2498d4c111453/rust/core-lib/src/lib.rs#L90)

**Comment by cmyr** [comment]
Anyone interested: this is only really a problem for people developing a frontend. Adding a print_err! here would be a good first step.

**Comment by zombiefungus** [comment]
Is this noob-could-fix (like myself) issue?

**Comment by cmyr** [comment]
@zombiefungus yes, this should be a very simple change. Let me know if you have any questions, or ask in the irc channel (irc.mozilla.org, #xi)
