### ISSUE TITLE
crash on move_to_end_of_line after (multiple?) undos

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#265]
reproduction:
- open a new document
- start typing, deleting occasionally to make sure you have multiple undo groups
- undo, type, undo,  type a few times
- use `ctrl-a`, `ctrl-e` (xi-mac) to move to the start or end of the line
- crash?

I do not have any additional insight into this issue at this time.

**Comment by raphlinus** [comment]
Minimal repro: `a`, undo, `ctrl-a`. This is actually fixed by #259. Underlying problem is that the single cursor and multi cursor state got out of sync.
