### ISSUE TITLE
 xcodebuild    no-   cargo  

### ISSUE THREAD

**Issue by ok2fly** [google/xi-editor#27]
/Users/d/xi-editor/xicore.sh: line 43: cargo: command not found

whether use xcode  or  run xcodebuild in terminal   ，there always have the problem above here。

which means cargo is not exist in default， to solve it ，you should install cargo  with Macport by running “ sudo port install cargo ”  if you have installed macport 。  after a few minute   cargo installation will be。

then everything will goes  well   。wish this will help

**Comment by raphlinus** [comment]
Or you can install with [brew](http://brew.sh/), or by following the instructions on [rust-lang.org](https://www.rust-lang.org). I tried to be pretty clear and explicit about this in the readme, but I know that first-time build is often a frustrating experience.

**Comment by shssoichiro** [comment]
A note for users of multirust/rustup as well: If XCode doesn't pick up your modified PATH containing `cargo` and `rustc`, the solution I used was to create symlinks for `cargo` and `rustc` in `/usr/local/bin`.
