### ISSUE TITLE
Frontend scroll position gets de-synchronized from correct position

### ISSUE THREAD

**Issue by trishume** [google/xi-editor#271]
With `google/xi-mac` f5fdae653b1ddc3229fe67a3e529b2e35a119ed7 and `xi-editor` d6c2d538e75594de0430dcd888bc362d5bd5ce59, sometimes clicking the cursor causes the view to show a completely different set of text and then place a cursor. It shows the same line numbers, and according to Sublime the text I see after I click is the correct text for that line number.

Steps to reproduce (not necessarily minimal, some may be unnecessary):
- Open a large Rust file (I use parser.rs from `rustc`)
- Scroll around a little bit
- Enable the `syntect` plugin.
- Scroll around very quickly, I use repeated accelerated swipes on a mac trackpad
- Click to place a cursor
- Text in view sometimes completely changes

It seems like the text in the frontend cache is the wrong lines relative to the correct text.

**Comment by raphlinus** [comment]
Yes, I can repro, but not super reliably. I wonder what's going on.
