### ISSUE TITLE
Cannot save an existing file to a new location

### ISSUE THREAD

**Issue by cbrewster** [google/xi-editor#273]
Steps to reproduce:
1. Open an existing file.
2. Do `Save As...` (on xi-mac)
3. Save as a new file that does not already exist.

The file is not saved to the new location and you can no longer edit any open files.

**Comment by cmyr** [comment]
Okay I'm not totally surprised something in there broke, probably related to my recent `BufferContainer` addition. You're welcome to investigate, or I'll take a look a bit later on.

**Comment by cbrewster** [comment]
It could also be something on the `xi-mac` end, not sure.

**Comment by cmyr** [comment]
fixed in #274
