### ISSUE TITLE
implement `Default` for `Rope`

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#283]
Small ergonomic improvement in `xi-rope`: The `Rope` type should implement [`Default`](https://doc.rust-lang.org/std/default/trait.Default.html), which would return `Rope::from("")`.

**Comment by palango** [comment]
Seems like `Default` is already implemented for `Node<N>`, see https://docs.rs/xi-rope/0.2.0/xi_rope/tree/struct.Node.html

`let r = xi_rope::rope::Rope::default();` works as well and returns a length of zero as expected.

**Comment by cmyr** [comment]
okay cool, hadn't noticed that. Thanks!
