### ISSUE TITLE
Use unicode-segmentation 1.2 for grapheme cluster boundaries

### ISSUE THREAD

**Issue by raphlinus** [google/xi-editor#298]
Version 1.2 of [unicode-segmentation](https://crates.io/crates/unicode-segmentation) has a rope-aware grapheme segmentation API. Change the `Rope::prev_grapheme_offset` and `next_grapheme_offset` functions to use this API rather than just advancing by codepoint.

**Comment by peterschussheim** [comment]
@raphlinus Can I work on this one?

**Comment by raphlinus** [comment]
@peterschussheim Would be happy to have you on board!
