### ISSUE TITLE
implement `cancel_operation` method

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#324]
Sent on `esc`. Exact operation is debatable, but should probably collapse multiple cursors, and probably collapse selections.

**Comment by rkusa** [comment]
+ Maybe remove search highlights

**Comment by sieut** [comment]
Hi, I'd like to start contributing to the project and will love to work on this one. I'm new to the project so it would be great if someone could give some instructions of where to start, etc. Thank you :)

**Comment by cmyr** [comment]
@sieut hello! noticed your message in IRC but nobody was around. Sorry about that. :)

I think that this would be an excellent issue to get started on, although there will be some trickiness around exactly what behaviour `esc` should cover.

As a first step, you should look at how editor commands are currently implemented: they're mostly defined in [rpc.rs](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/rpc.rs), and then handled in [editor.rs](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/editor.rs). Based on that you should be able to add `cancel_operation`.

The bigger question is what exactly `cancel_operation` should do. The general strategy here would be to fire up a number of other editors (with sublime text being our sort of informal reference editor) and looking at their behaviour.

I wouldn't be surprised if there's a little bit of trickiness in getting this just right, but it should be a good way of starting to explore the codebase. Feel free to try here or IRC if you have any questions, although here might be better at the moment since everyone's focus is a bit split at the moment.
