### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by hholst80** [google/xi-editor#334]
master 3f157ff0601faf8a94f6c56dd07c1de45323f062

```
$ cargo build --verbose
failed to parse registry's information for: serde_json

Caused by:
  the given version requirement is invalid
```

**Comment by cmyr** [comment]
@hholst80 what version of cargo + rustc are you running? Is it 1.17+?

**Comment by cmyr** [comment]
@hholst80 will close this in a bit unless I hear that it's still an issue.
