### ISSUE TITLE
find creates unexpected selections

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#346]
When there are no find results for a string, but there were find results for some intermediate version of that string, one of those intermediate results remains highlighted.

![screen recording 2017-06-22 at 04 50 pm](https://user-images.githubusercontent.com/3330916/27455437-3da3bd1a-576b-11e7-9962-b6df57dc1bfe.gif)

**Comment by shnupta** [comment]
This may be something to do with using the last selection when a search string isn't provided. Look here: https://github.com/google/xi-editor/blob/master/rust/core-lib/src/editor.rs#L874

I'm not home for a couple days but will be happy to take a look when I'm back!

**Comment by scholtzan** [comment]
This has been resolved in https://github.com/google/xi-editor/pull/687 and can be closed.
