### ISSUE TITLE
syntect plugin is missing spans

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#352]
With syntect enabled, some text regions are missing spans. I’m not sure yet if this is a regression: to be visible it requires using a theme where the normal text color is distinct from the system default text color.

In xi-mac, text with no associated spans is drawn using the default foreground color by default, so this isn’t especially visual. When I disable that, and draw unstyled text in another color, it looks like this:

(to reproduce these screenshots, comment out the line `attributes[NSForegroundColorAttributeName] = textColor` in `TextDrawingMetrics` in `EditView.swift`, line 55 as of this writing.)

![screen shot 2017-06-30 at 9 56 08 am](https://user-images.githubusercontent.com/3330916/27738831-94012c96-5d7a-11e7-8ad2-cde187bc24f8.png)
![screen shot 2017-06-30 at 9 56 17 am](https://user-images.githubusercontent.com/3330916/27738832-954ce9be-5d7a-11e7-81e2-cde2c3e4263d.png)
![screen shot 2017-06-30 at 10 01 12 am](https://user-images.githubusercontent.com/3330916/27739079-686e6dcc-5d7b-11e7-98cf-cbc22fd6eaa1.png)

**Comment by eyelash** [comment]
I noticed that all the examples above are at the end of the line. Could this be something to do with styles that span multiple lines but are only sent for the last line?

**Comment by cmyr** [comment]
@eyelash Interesting theory. I definitely need to revisit this one soon, hadn't meant for it to sit this long.
