### ISSUE TITLE
add top level ‘init’ RPC method

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#353]
A small proposed addition to the client protocol: the client, on launch, sends some sort of `client_init` RPC request or notification (tbd). Eventually I could imagine this having some useful payload (an opportunity for the client to pass some config options for example) although currently it would be an empty object. This would be an opportunity for core to do any one-time tasks; the specific use-case right now would be sending the client a list of available themes.

The reason this requires a new RPC is that core doesn’t have access to the `RpcPeer` used for sending RPCs until the client has created a view, so the core can’t initiate an RPC.

### Alternatives

1. If the core (in the form of the `Documents<W>` object) owned a copy of the `RpcPeer`, then the core could initiate communication.

2. The core could send this sort of information when the first view is added.

The first of these is a reasonable alternative, if we don’t think there’s ever going to be a need for the client to send config information. The second has some drawbacks, like the core not being able to talk to the client if the application is open without any open views.

**Comment by raphlinus** [comment]
Adding an init method seems quite reasonable to me. This also seems like something we can change later if there's a compelling reason to do so.

**Comment by ax487** [comment]
Just a couple of questions:

- As far as I can see there is no client state management in xi so far. So there is no way to find out whether some session has been initialized already when a command is sent or whether a session was initialized twice, etc. Should this functionality be added?
- What names / formats would you suggest for the messages?

**Comment by cmyr** [comment]
1. If we're using an overt init message I don't think this is necessary. It should be an invariant that the first message a client sends after connecting is the init message.

2. If I were doing this right this second I think I would go with `client_started: {}` that is: params are an empty object.

**Comment by ax487** [comment]
@cmyr: Could you take a look at my attempt [here](https://github.com/ax487/xi-editor)? I would like to write a test for it, but as far as I can see the test framework is being [refactored](https://github.com/google/xi-editor/issues/249). Also I have not seen any test cases or documentation so far?!

**Comment by cmyr** [comment]
@ax487 I'll take a look first thing tomorrow. :)

the issue you linked to only applies to the python plugin library. xi-core isn't very heavily tested right now. (there are a few tests scattered around, you can see by running `cargo test` in the `core-lib` directory)

**Comment by cmyr** [comment]
@ax487 looks about right to me. I wouldn't use `server_init_response`; instead I would add a new notification to the client protocol called `available_themes`, which contains a list of available theme names, and I would send that. We will also use this method to notify the client when themes have been added or removed.

If I were reviewing this as a PR, I would also suggest that your `get_theme_names` method should just return a `Vec<String>`.

**Comment by ax487** [comment]
Ok, I hope the current version is what you had in mind.

**Comment by cmyr** [comment]
@ax487 left a comment on that commit, in case  you missed it :)

**Comment by cmyr** [comment]
this is added in #386
