### ISSUE TITLE
Implement delete_word_forward and delete_word_backward

### ISSUE THREAD

**Issue by jansol** [google/xi-editor#361]
In many editors, alt+backspace/delete deletes a word starting from the cursor position. Seeing as moving the cursor left/right and selecting by word is supported, I'd expect deletion to work the same way.

**Comment by cmyr** [comment]
This is definitely something to implement, it just hasn't been gotten around to. If anyone would like to take a stab at it it should be very doable.

**Comment by callodacity** [comment]
I have a solution for this, will make a PR shortly 👍
