### ISSUE TITLE
Getting Error on running cargo build command in UBUNTU

### ISSUE THREAD

**Issue by shubham1109** [google/xi-editor#375]
Error is shown like this...

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/zlib.rs:202:9
    |
202 |     pub(crate) fn read_from<R>(mut reader: R) -> io::Result<Self>
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/gzip.rs:98:5
   |
98 | pub(crate) struct Trailer {
   |     ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/gzip.rs:370:9
    |
370 |     pub(crate) fn read_from<R>(mut reader: R) -> io::Result<Self>
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/deflate/mod.rs:29:5
   |
29 | pub(crate) mod symbol;
   |     ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/non_blocking/deflate/decode.rs:72:9
   |
72 |     pub(crate) fn bit_reader_mut(&mut self) -> &mut TransactionalBitReader<R> {
   |         ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/non_blocking/deflate/decode.rs:117:60
    |
117 |                     DecoderState::ReadNonCompressedBlock { len }
    |                                                            ^^^

error: struct field shorthands are unstable (see issue #37340)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/non_blocking/transaction.rs:15:34
   |
15 |         TransactionalBitReader { inner, savepoint }
   |                                  ^^^^^

error: struct field shorthands are unstable (see issue #37340)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/non_blocking/transaction.rs:15:41
   |
15 |         TransactionalBitReader { inner, savepoint }
   |                                         ^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/non_blocking/transaction.rs:68:13
   |
68 |             inner,
   |             ^^^^^

error: struct field shorthands are unstable (see issue #37340)
  --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:79:13
   |
79 |             inner,
   |             ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:143:9
    |
143 |     pub(crate) fn state(&self) -> BitReaderState {
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:150:9
    |
150 |     pub(crate) fn restore_state(&mut self, state: BitReaderState) {
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:171:5
    |
171 | pub(crate) struct BitReaderState {
    |     ^^^^^

error: aborting due to 13 previous errors

**Comment by mrandri19** [comment]
Check your rust compiler's version, it may be outdated
