### ISSUE TITLE
Can't Input Hard Tabs

### ISSUE THREAD

**Issue by OxyDeadbeef** [google/xi-editor#381]
Pressing tab always gives 4 spaces.

**Comment by cmyr** [comment]
Yea this is a current limitation, and can be addressed when we add user preferences. We should also probably add per-buffer tab preferences at some point.

**Comment by linde12** [comment]
I solved this temporarily in the client by sending `\t`. I then render it like four spaces but treat it like a single character so that i can, e.g., still remove it by pressing backspace just once.

I imagine the core will do something similar to this. Looking forward to it!

**Comment by raphlinus** [comment]
Agree this is important. It does need to be per-buffer because different languages have different requirements (I believe they're more or less mandatory for go and make, while for example Python's PEP8 recommends spaces). It's also related to a setting for the tab indent; 4 spaces is common but not universal.

I can't say exactly when we'll get to this. As @cmyr points out, it's not quite self-contained but depends on some mechanism for preferences.

**Comment by OxyDeadbeef** [comment]
I'd like to point out that, as far as I know, no programming language requires a specific type of indentation.  Some have "preferred" indentation, but that doesn't really mean anything.

Changing tab input settings wouldn't necessarily require a preferences menu, but could do something similar to gedit:

![screenshot from 2017-08-17 22-24-12](https://user-images.githubusercontent.com/8846235/29443027-e311db6e-839a-11e7-89ab-725f349a563b.png)

**Comment by joerixaop** [comment]
That depends on whether you consider Makefiles a language

**Comment by NatElkins** [comment]
@OxyDeadbeef F# requires tabs.
![tabs](https://user-images.githubusercontent.com/1795462/29576909-92abd9ae-8737-11e7-8550-40f539cc2542.gif)

Like the gif says, it can be turned off with the `#indent "off"` directive, but code with tabs won't work out of the box.

**Comment by maxnordlund** [comment]
[Gofmt](https://golang.org/cmd/gofmt/) also uses tabs for indentation.

**Comment by eyelash** [comment]
Since #409 landed you can create a file `~/.config/xi/preferences.xiconfig` with the content
```
translate_tabs_to_spaces = false
```
which will cause Xi to input tabs when you press tab.

**Comment by cmyr** [comment]
As @eyelash mentions, while the ergonomics aren't great, there is now a user setting for tabs vs spaces, which I think is enough to close this issue. On xi-mac, as of https://github.com/google/xi-mac/pull/71, tabs and spaces can now be set (crudely) on a per-file basis.
