### ISSUE TITLE
Clarification in update.md

### ISSUE THREAD

**Issue by linde12** [google/xi-editor#385]
I'd love to see some more clarification on how "updates" (`update` requests from xi-core to frontend) should be handled.

It's really nice that xi-mac is open source so that we can inspect the source and see how it's done by example, but i would really like to get a more in-depth understanding of how it works.

Maybe some explanation in `update.md` and/or more comments in xi-mac would suffice.

The reason why i want to know is that í'm trying to work on a frontend written in Go as a hobby project, and would like to get a clear picture of how i should handle these update requests. I understand if these docs are not the highest priority at the moment, but if you find the time i'd appreciate it a lot.

**Comment by linde12** [comment]
Just noticed that this was a part of the roadmap! See #252 "stabilization and good documentation of front-end protocol"

**Comment by cmyr** [comment]
@linde12 sorry for the slow response. :) the lack of documentation is closely tied to things being in flux. Your best bet, as you've figured out, is `update.md` and reading the source of existing clients. If you have any particular questions, feel very free to ask them here or on the irc. :)
