### ISSUE TITLE
weird update after resize

### ISSUE THREAD

**Issue by little-dude** [google/xi-editor#407]
Hi,

I'm being confused by an update sent by the core.

Here is the file I use to reproduce:

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddd
eeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ffffffffffffffffffffffffffffff
gggggggggggggggggggggggggggggg
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
iiiiiiiiiiiiiiiiiiiiiiiiiiiiii
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
llllllllllllllllllllllllllllll
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
oooooooooooooooooooooooooooooo
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
ssssssssssssssssssssssssssssss
```

I first send a request to open a view:

```
>>> {"id":1,"method":"new_view","params":{"file_path":"test"}}
```

The core answers the request to open a view, and sends an update with 12 lines to insert. At this point my cache has 12 lines,

```
<<< {"id":1,"result":"view-id-1"}
<<< {"method":"available_plugins","params":{"plugins":[],"view_id":"view-id-1"}}
<<< {"method":"update","params":{"update":{"ops":[{"lines":[{"cursor":[0],"styles":[],"text":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"},{"styles":[],"text":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n"},{"styles":[],"text":"cccccccccccccccccccccccccccccc\n"},{"styles":[],"text":"dddddddddddddddddddddddddddddd\n"},{"styles":[],"text":"eeeeeeeeeeeeeeeeeeeeeeeeeeeeee\n"},{"styles":[],"text":"ffffffffffffffffffffffffffffff\n"},{"styles":[],"text":"gggggggggggggggggggggggggggggg\n"},{"styles":[],"text":"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh\n"},{"styles":[],"text":"iiiiiiiiiiiiiiiiiiiiiiiiiiiiii\n"},{"styles":[],"text":"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjj\n"},{"styles":[],"text":"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh\n"},{"styles":[],"text":"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\n"}],"n":12,"op":"ins"},{"n":8,"op":"invalidate"}],"pristine":true},"view_id":"view-id-1"}}
<<< {"method":"scroll_to","params":{"col":0,"line":0,"view_id":"view-id-1"}}
```

notify the core that we actually have a 21 lines high scroll region for the real view:
```
>>> {"method":"edit","params":{"method":"scroll","params":[21,80],"view_id":"view-id-1"}}
```

The core answers with an update with 19 lines to copy, but my cache has only 12 at that point:

```
<<< {"method":"update","params":{"update":{"ops":[{"n":19,"op":"copy"},{"lines":[{"styles":[],"text":""}],"n":1,"op":"ins"},{"n":1,"op":"skip"}],"pristine":true},"view_id":"view-id-1"}}
```

I'm not sure what to do here. For the moment I copy 12 lines, and mark 7 lines
as invalid. Then I insert 1 empty lines, and skip 0 line (since I don't have
any more lines to skip).

There are two issues here:

- the operations I perform are weird
- in the end, I have only 13 valid lines (the last being empty), whereas I have
  enough space display them all.

**Comment by cmyr** [comment]
Here is the startup sequence on xi-mac. 

```javascript
{"method":"client_started","params":{}}
{"method":"set_theme","params":{"theme_name":"base16-ocean.light"}}
{"id":0,"method":"new_view","params":{"file_path":"\/Users\/cmyr\/Dev\/hacking\/xi-mac\/test.txt"}}
{"method":"edit","params":{"view_id":"view-id-1","method":"scroll","params":[0,51]}}
{"method":"edit","params":{"view_id":"view-id-1","method":"request_lines","params":[12,20]}}
{"method":"close_view","params":{"view_id":"view-id-1"}}
```

I remember running into something like this when i was first working on the xi-mac client. There is something in here that's weird. I remember it's important to send `scroll`, which also serves as a "set viewport" method.

**Comment by eyelash** [comment]
```json
{
  "ops": [
    {
      "lines": [
        {"cursor":[0],"styles": [],"text": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"},
        {"styles":[],"text": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n"},
        {"styles":[],"text":"cccccccccccccccccccccccccccccc\n"},
        {"styles":[],"text":"dddddddddddddddddddddddddddddd\n"},
        {"styles":[],"text":"eeeeeeeeeeeeeeeeeeeeeeeeeeeeee\n"},
        {"styles":[],"text":"ffffffffffffffffffffffffffffff\n"},
        {"styles":[],"text":"gggggggggggggggggggggggggggggg\n"},
        {"styles":[],"text":"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh\n"},
        {"styles":[],"text":"iiiiiiiiiiiiiiiiiiiiiiiiiiiiii\n"},
        {"styles":[],"text":"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjj\n"},
        {"styles":[],"text":"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh\n"},
        {"styles":[],"text":"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\n"}
      ],
      "n":12,
      "op":"ins"
    },
    {
      "n":8,
      "op":"invalidate"
    }
  ],
  "pristine":true
}
```

If you take a closer look at the first response from the core you notice that it contains two operations. One to insert 12 lines and one to invalidate 8 lines, so your cache actually contains 20 lines after that (even though 8 of those are invalid).

That said, there are still issues with the update protocol such as #270.

**Comment by raphlinus** [comment]
The @eyelash seems correct to me. "copy" does mean "preserve the existing state of that line" whether the state is valid or no.

Big improvements are coming before long to the update protocol. The main tracking bug is #317.

**Comment by little-dude** [comment]
Hi,

Thanks for all the response, and sorry for forgetting to take invalid lines into accounts.
I changed my code, but I'm still seeing one issue.
The test file is changed a little:

```
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
```

Here is the full exchange:

```
>>> {"id":1,"method":"new_view","params":{"file_path":"test"}}
<<< {"id":1,"result":"view-id-1"}
<<< {"method":"available_plugins","params":{"plugins":[],"view_id":"view-id-1"}}
<<< {"method":"update","params":{"update":{"ops":[{"lines":[{"cursor":[0],"styles":[],"text":"a\n"},{"styles":[],"text":"b\n"},{"styles":[],"text":"c\n"},{"styles":[],"text":"d\n"},{"styles":[],"text":"e\n"},{"styles":[],"text":"f\n"},{"styles":[],"text":"g\n"},{"styles":[],"text":"h\n"},{"styles":[],"text":"i\n"},{"styles":[],"text":"j\n"},{"styles":[],"text":"k\n"},{"styles":[],"text":"l\n"}],"n":12,"op":"ins"},{"n":15,"op":"invalidate"}],"pristine":true},"view_id":"view-id-1"}}
<<< {"method":"scroll_to","params":{"col":0,"line":0,"view_id":"view-id-1"}}
>>> {"method":"edit","params":{"method":"scroll","params":[22,180],"view_id":""}}
>>> {"method":"edit","params":{"method":"scroll","params":[22,180],"view_id":"view-id-1"}}
<<< {"method":"update","params":{"update":{"ops":[{"n":20,"op":"copy"},{"lines":[{"styles":[],"text":"u\n"},{"styles":[],"text":"v\n"},{"styles":[],"text":"w\n"},{"styles":[],"text":"x\n"},{"styles":[],"text":"y\n"},{"styles":[],"text":"z\n"},{"styles":[],"text":""}],"n":7,"op":"ins"},{"n":7,"op":"skip"}],"pristine":true},"view_id":"view-id-1"}}
```

First update (before I send `scroll`):


```json
{
  "method": "update",
  "params": {
    "update": {
      "ops": [
        {
          "lines": [
            {"cursor": [0], "styles": [], "text": "a\n"},
            {"styles": [], "text": "b\n"},
            {"styles": [], "text": "c\n"},
            {"styles": [], "text": "d\n"},
            {"styles": [], "text": "e\n"},
            {"styles": [], "text": "f\n"},
            {"styles": [], "text": "g\n"},
            {"styles": [], "text": "h\n"},
            {"styles": [], "text": "i\n"},
            {"styles": [], "text": "j\n"},
            {"styles": [], "text": "k\n"},
            {"styles": [], "text": "l\n"}
          ],
          "n": 12,
          "op": "ins"
        },
        {
          "n": 15,
          "op": "invalidate"
        }
      ],
      "pristine": true
    },
    "view_id": "view-id-1"
  }
}

```

Cache after the first update:

- invalid before: 0
- lines: `a\n` to `l\n`
- invalid after: 15,

Second update (after I sent `scroll`):

```json
{
  "method": "update",
  "params": {
    "update": {
      "ops": [
        {
          "n": 20,
          "op": "copy"
        },
        {
          "lines": [
            {"styles": [], "text": "u\n"},
            {"styles": [], "text": "v\n"},
            {"styles": [], "text": "w\n"},
            {"styles": [], "text": "x\n"},
            {"styles": [], "text": "y\n"},
            {"styles": [], "text": "z\n"},
            {"styles": [], "text": ""}
          ],
          "n": 7,
          "op": "ins"
        },
        {
          "n": 7,
          "op": "skip"
        }
      ],
      "pristine": true
    },
    "view_id": "view-id-1"
  }
}
```
Here is how I proceed to build the new cache:

- new cache after `copy`:
    - invalid before: 0
    - lines: `a\n` to `l\n` (12 lines copied)
    - invalid after: 8 (8 lines copied)
- new cache after `insert`:
    - invalid before: 0
    - lines: `a\n` to `l\n` + `u\n` to `z\n` + "" (7 lines inserted)
    - invalid after: 8
- new cache after `skip` (nothing changes, because I skip the 7 invalid lines remaining in the old cache):
    - invalid before: 0
    - lines: `a\n` to `l\n` + `u\n` to `z\n` + ""
    - invalid after: 8

final cache:

- invalid before: 0
- lines: `a\n` to `l\n` + `u\n` to `z\n` + ""
- invalid after: 8 

The lines I display are:

```
a
b
c
d
e
f
g
h
i
j
k
l
u
v
w
x
y
z

```

As you can see:

- "m\n" to "t" are missing.
- my cache has more lines (20 valid + 8 invalid) than the file (26)

Am I missing another subtlety?

**Comment by eyelash** [comment]
The `insert` operation really inserts at the end of the cache (after the invalid lines) so the cache after `insert` should look like this:
- invalid before: 0
- lines: `a` to `l` + 8 invalid lines + `u` to `z` + ""
- invalid after: 0

The `skip` operation does not change the cache so your final cache has 27 lines. By the way the cache always spans the whole document so the number of lines the cache has is always equal to the number of lines in the document (it is always 27 for your example document).

**Comment by little-dude** [comment]
I didn't realize we could have "holes" in the valid lines. I guess it makes sense for things like folding.
However, I wonder how I'm supposed to diplay this cache now: I have 22 lines, so I'd like to diplay `a` to `v`, but I can't.

**Comment by raphlinus** [comment]
The `request-lines` RPC is for requesting lines that you don't have in your cache. This is asynchronous, though, so it's likely to lead to displaying blank lines until the `update` comes back in response to that. I'm likely to bring back a synchronous RPC.

I'm a little curious though, why do you want to display these lines when they're outside your scroll location? The basic theory is that the core tries to keep lines inside the scroll region updated, and outside that it's "best-effort" (and currently not very good at that, even cursor movement causes invalidation).

The update protocol seems to generate a lot of confusion for just about everybody doing a front-end. I think I need to improve the documentation around it; perhaps that's something that would make sense around the same time #270 and #317 get done (the former in particular will subtly change the expectations around front-end invalidity from where they are now).

**Comment by eyelash** [comment]
@little-dude in your example above the front-end sends a `scroll` with `"params":[22,180]`, so the core assumes that you want to show the lines 22 to 180, so the response from the core is an `update` that makes sure lines 22 to 26 (`w` to the end of the document) are up to date in the cache, which they are after the `update`. Now when you want to display, you just retrieve the lines 22 to 180 from the cache. Make sure you take `invalid before` into account when retrieving lines from the cache. In this example it doesn't matter because it is 0 but in general it does. See [here](https://github.com/eyelash/xi-gtk/blob/962bf22a924b257915f7a8b47abefb5f015a3bb7/src/LineCache.vala#L125-L130) for an example implementation.

**Comment by little-dude** [comment]
I feel dumb now: I was giving `[nb_lines, nb_columns]` as argument to `scroll`... No idea why, because in the first iteration of `xi-tui` I got this right. Thanks for your explanation @eyelash !

I fixed the cache and scrolling logic in my frontend already.

Thanks for your patience everyone, I'm closing this.
