### ISSUE TITLE
core becomes non-responsive when receiving unrecognized RPC

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#434]
Noticed in the process of updating xi-mac to use some more of the new config stuff.

In the main loop the outer thread joins the inner thread before returning, but the inner thread doesn't know that parsing has failed.

This is a bug; at the very least this should print an error and panic.

**Comment by cmyr** [comment]
This bug is my fault and I'll get to it eventually but if anyone wants to take a shot they're welcome. ;)

**Comment by leethomas** [comment]
How would I reproduce this? I tried to reproduce by doing this

```rst
let json = make_reader(r#"{"method":"this definitely does not exist","params":{}}
{"method":"garbage","params":{"theme_name":"InspiredGitHub"}}"#);
    rpc_looper.mainloop(|| json, &mut state).unwrap();
``` 

but it panicked in a sane way
```
	thread 'test_startup' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownRequest(ErrorImpl { code: Message("unknown variant `swaaaaaag`, expected one of `edit`, `plugin`, `close_view`, `save`, `set_theme`, `client_started`, `modify_user_config`"), line: 0, column: 0 })'
```

has this been fixed already?

**Comment by cmyr** [comment]
@leethomas the problem with your example is that mainloop returns when it hits EOF on the json; in normal usage the stream doesn't end, so the inner loop doesn't return, so we don't see the error message. To reproduce just run xi-core from the command line, and then pass an unknown RPC via stdin.
