### ISSUE TITLE
Breaking changes coming up

### ISSUE THREAD

**Issue by raphlinus** [google/xi-editor#44]
I want to make some big changes, especially in the FE/BE protocol, after which hopefully it will stabilize for a while. A main motivation is to support multi-window / multi-tab. While I'm making those changes, I'd like to roll in some other stuff to make it cleaner. So:

* Get rid of the 8 byte framing (issue #29) and move to something closer to JSON-RPC (see issue #2). When I look closely at JSON-RPC, I see some fragmentation, and there's nothing that's exactly what I need, so I'm inclined to mix and match. I do want to unify the syntax of sync and async calls (and a bunch of calls that are now async should become sync so they can return errors, like open/save). The details don't matter so much for FE/BE, but they do matter a lot for plugins (see #43), and it would be ugly for the two to use different low-level mechanism. So what I'm looking at is basically JSON-RPC 2 syntax, minus the `"jsonrpc": "2.0"` (there's no need to version-negotiate, and signalling strict compatibility with the spec is misleading), with requests allowed in both directions. I don't want to rule out binary stuff in the future, but it's better to start with something clean.

* All requests in both directions grow a "tab" field, which identifies a tab with a unique identifier. I'm thinking this should be a string derived from the file name (but guaranteed unique) to make debugging more friendly. I've also considered having a two-level structure, with the outer layer identifying the tab and having only a small number of commands, and dispatching the inner message, but I don't think that's better. Obviously `main.rs` will no longer plumb directly to the editor, but will need to go through a lookup based on tab before dispatching to the editor.

* `do_key` should probably go away, and I should just add menu items (maybe in a Developer tab which would be optional for end users).

I know people are working on stuff this might break, which is one reason I'm discussing it before diving in.

**Comment by Sineaggi** [comment]
I like the sound of this.

Does this mean we'll be waiting for an end-of-stream signal? How do you think client/server side buffer allocation should work? Set up arrays on both sides of certain lengths, and pray we don't ever exceed those lengths? Will we also be removing the '\n' newline character at the end of the json?

Re issue #29, if we ever were to move to a full binary format, I'd imagine even more Windows issues arriving, so removing the framing would only work until a binary format is proposed. I'd much rather figure out what's going wrong and fix it, so that if you do want to keep the 8 byte frame, it would work regardless.

**Comment by raphlinus** [comment]
No, the `\n` will remain, and will signal the end of the command. In the Rust implementation of stdin/stdout, this works well - the `BufRead` trait has a `read_line` method, and stdout wraps a `LineWriter`, which we were paying for anyway, even though we didn't need it. My feeling is that it's much cleaner to go text-only for stdin/stdout, and if and when we need binary, embrace that directly. Obviously the problem of making the channel binary-clean can and should be solved.

Getting into the code, I think I'll change my mind on the wrapping of tab commands, as having it on a single level would mean I need to dispatch twice on a large number of cmds. I'm now looking at:

```
{method: "edit_cmd", "params": {"tab": "1", "cmd": "insert", "params": ["hello"]}, "id": "42"}
```
