### ISSUE TITLE
Ctrl-DoubleClick replaces selection instead of adding

### ISSUE THREAD

**Issue by WesleyAC** [google/xi-editor#444]
Not sure if this is a bug in xi-gtk or xi-core, but holding control while double-clicking selects the word and removes other cursors - IMO it should add a selection (this is sublime's behaviour). There is the same issue with triple-click.

Filing this on xi-core since it looks like all the clicking logic is in `do_click` in `editor.rs`, but I'm not sure if the frontend is supposed to send a different RPC on ctrl-click.

**Comment by raphlinus** [comment]
It straddles both. What should happen is that this mouse gesture gets migrated from `do_click` to `do_gesture`, and that `do_gesture` grows to be able to handle it. Actually I'd like to migrate _all_ gestures off of `do_click` but have been lazy.

This feels like a good thing to work on :)

**Comment by wuweiweiwu** [comment]
@cmyr @raphlinus On it!

**Comment by rscircus** [comment]
@wuweiweiwu did you start working on this?

Else, I'd like to collaborate and/or take over here, as suggested in https://twitter.com/cmyr/status/975728008546963456 :-)

Meanwhile, I'll try to grok @raphlinus suggestion to migrate all gestures off of `do_click`.

**Comment by wuweiweiwu** [comment]
@rscircus Please do! I've been swamped at work unfortunately :(

**Comment by rscircus** [comment]
Alright, onboarding. I'll come back to you, when this hits review-time maybe? :yum:

**Comment by scholtzan** [comment]
Oh, I added a fix for this issue without seeing that you (@rscircus) wanted to work on this issue. Sorry! In case you already started working on this, feel free to give feedback and suggestions to my pull-request. I think there might be room for improvements.

**Comment by rscircus** [comment]
Haha, @scholtzan, actually I grabbed this issue from somebody else already. :) Now you just finished it off. Actually, I'm midway in solving it. Had to fix some issues with xi-gtk first as my platform didn't like anything and I'm learning Rust and thought this to be a nice motivation. Having said that, I'm maybe not the best reviewer. I'll have a look at your solution and would be happy if you answer my questions?! Maybe that helps in some kind of pair programming way...

**Comment by scholtzan** [comment]
That sounds good! I'd be happy to answer your questions.

**Comment by rscircus** [comment]
Alright :) I added a few remarks in your PR without starting a review.

**Comment by cmyr** [comment]
@rscircus if you've already been working in this area, we do still have the related issue of migrating the `do_click` RPC to be a gesture, if you'd like to work on that?
