### ISSUE TITLE
 cargo build Could not compile `plist`.

### ISSUE THREAD

**Issue by myvker** [google/xi-editor#446]
cargo build

error: aborting due to previous error

error: Could not compile `plist`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by cmyr** [comment]
@myvker What platform are you on, and what version of rustc are you using?

**Comment by myvker** [comment]
windows 10 x64  and Rust 1.22.1

**Comment by cmyr** [comment]
@myvker ah interesting, plist shouldn't be trying to compile on windows I don't think. Can you post the full output of `cargo build`?

**Comment by myvker** [comment]
@cmyr 


user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi
$ git clone https://github.com/google/xi-editor.git
Cloning into 'xi-editor'...
remote: Counting objects: 5746, done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 5746 (delta 77), reused 80 (delta 56), pack-reused 5633
Receiving objects: 100% (5746/5746), 3.91 MiB | 478.00 KiB/s, done.
Resolving deltas: 100% (3906/3906), done.

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi
$ ls
xi-editor/

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi
$ cd xi-editor/

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi/xi-editor (master)
$ ls
CONTRIBUTING.md  LICENSE  README.md  doc/  icons/  python/  rust/

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi/xi-editor (master)
$ cd rust/

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi/xi-editor/rust (master)
$ ls
BUILD.gn    Cargo.toml  experimental/  rope/  src/             unicode/
Cargo.lock  core-lib/   plugin-lib/    rpc/   syntect-plugin/

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi/xi-editor/rust (master)
$ cargo build
   Compiling safemem v0.2.0
   Compiling lazy_static v0.2.11
   Compiling dtoa v0.4.2
   Compiling adler32 v1.0.2
   Compiling unicode-xid v0.0.4
   Compiling serde v1.0.21
   Compiling winapi v0.2.8
   Compiling libc v0.2.33
   Compiling bitflags v0.7.0
   Compiling num-traits v0.1.40
   Compiling bytecount v0.1.7
   Compiling itoa v0.3.4
   Compiling byteorder v1.1.0
   Compiling build_const v0.2.0
   Compiling winapi-build v0.1.1
   Compiling cfg-if v0.1.2
   Compiling quote v0.3.15
   Compiling bitflags v1.0.1
   Compiling xi-unicode v0.1.0 (file:///C:/opt/xi/xi-editor/rust/unicode)
   Compiling crossbeam v0.2.10
   Compiling plist v0.2.4
error: linking with `link.exe` failed: exit code: 1
  |
  = note: "link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\opt\\xi\\xi-editor\\rust\\target\\debug\\build\\plist-d2fcde2dbdd7a78c\\build_script_build-d2fcde2dbdd7a78c.build_script_build0.rust-cgu.o" "C:\\opt\\xi\\xi-editor\\rust\\target\\debug\\build\\plist-d2fcde2dbdd7a78c\\build_script_build-d2fcde2dbdd7a78c.build_script_build1.rust-cgu.o" "/OUT:C:\\opt\\xi\\xi-editor\\rust\\target\\debug\\build\\plist-d2fcde2dbdd7a78c\\build_script_build-d2fcde2dbdd7a78c.exe" "C:\\opt\\xi\\xi-editor\\rust\\target\\debug\\build\\plist-d2fcde2dbdd7a78c\\build_script_build-d2fcde2dbdd7a78c.crate.allocator.rust-cgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\opt\\xi\\xi-editor\\rust\\target\\debug\\deps" "/LIBPATH:C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-571928b9eba253d1.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-b4bd41caf6074e96.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librand-41112daf4169c38d.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-53d49172c207c98c.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-ee44bdc6692fd9c9.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-ede05b6f46264373.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_unicode-0639d4cde67a9493.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-78df137af729c1d4.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-e07db25254090156.rlib" "C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-a3d4cc1d8f3f719c.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: link: extra operand ‘/LIBPATH:C:\\Users\\user\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib’
          Try 'link --help' for more information.


error: aborting due to previous error

error: Could not compile `plist`.
warning: build failed, waiting for other jobs to finish...
error: build failed

user@DESKTOP-GJ6KPO0 MINGW64 /c/opt/xi/xi-editor/rust (master)
$

**Comment by sqweek** [comment]
Just cloned xi and having the same problem. I don't have vstudio installed so not sure why it's trying to invoke LINK.exe (In my case it's finding GNU link from mingw, which complains because there's more than two arguments).

**Comment by sqweek** [comment]
Ok it's because rust defaults to using the [MSVC toolchain](https://github.com/rust-lang/rust/pull/25350) - ie. target x86_64-pc-windows-msvc. I configured it to use mingw instead:

    $ rustup target add x86_64-pc-windows-gnu
    $ rustup toolchain install stable-x86_64-pc-windows-gnu
    $ rustup default stable-x86_64-pc-windows-gnu
    $ cargo build

rustup takes awhile, it has to download a bunch of stuff. I don't know if this is recommended practice, but xi-core.exe built fine after these steps so it seems this is a rust configuration issue and not a xi problem.

(now I guess I'm off to track down a windows front-end... :) )

**Comment by jansol** [comment]
Is this still an issue? AFAIK there have been major improvements to windows stuff on the rust side.

**Comment by betterclever** [comment]
It compiles for me in Windows.
