### ISSUE TITLE
(Docs) What is a base_unit?

### ISSUE THREAD

**Issue by Eh2406** [google/xi-editor#449]
[Metric](https://docs.rs/xi-rope/0.2.0/xi_rope/tree/trait.Metric.html) has a method to_base_units, but no info on what is a base_unit. What is it? How would a Metric use these functions?

**Comment by Eh2406** [comment]
looks like there is more info in the src that is not being displayed by rust doc. Perhaps it is `\\` instead of using `\\\`?

**Comment by Eh2406** [comment]
Conversation happening in irc https://botbot.me/mozilla/xi/2017-12-09/?msg=94473883

**Comment by cmyr** [comment]
resolved in #450
