### ISSUE TITLE
Can't backspace over text

### ISSUE THREAD

**Issue by marchelzo** [google/xi-editor#47]
Occasionally, I end up in a state where pressing backspace doesn't seem to work.

I'm able to reproduce it pretty consistently by doing this:

1. Open a reasonably large file (> 30 K)
2. Scroll to the very bottom
3. Quickly scroll to the middle of the file
4. Position the cursor at the end of a line
5. Try to backspace twice

The first backspace works, but then it stops working. I'm still able to insert text, and I can even delete the text if I make a visual selection and *then* press backspace. But after deleting it, I still can't backspace over the point where the text was.

**Comment by JesseFarebro** [comment]
Can reproduce.

Although step 2 you can scroll anywhere in the file quickly and you can experience the same behaviour. It doesn't have to be at the end of the file.
