### ISSUE TITLE
Add chrome tracing support

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#471]
In [xi-mac#103](https://github.com/google/xi-mac/pull/103) we added support for tracing using the [chrome trace format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview).

This should be rolled out to xi-core, and eventually plugins. I would defer on the plugin work initially, and implement this in xi-core.

So: we should be generating traces on an ongoing basis, and then in response to some new `dump_trace` RPC we should be _either_ writing them to a directory passed as an argument, or else returning them as a response. (It's unclear to me which of these is better; it comes down to whether the tools for viewing traces want a single file or not, probably)

Some questions:
- Do we want to have some global trace repository, or do we want to use some thread-local structure and synchronize only as needed?
- Do we want to include traces _in_ xi-rpc? If yes, this gets a bit more complicated; we'd need to add some mechanism for collecting these.
- Do we write to a file or return a response?

**Comment by vlovich** [comment]
Step 1 I'll be working on is the base tracing API.  It will be a standalone library crate that works as follows:

1. Use time::precise_time_ns from the time crate as the timestamp basis.
2. Events are either instantaneous or a start/stop block.  The API usage would be:
```
{
   let _guard = xi_perf::trace_block("some thing");
   some_expensive_operation();
}
xi_perf::trace_instant("some other thing");
```
Tracing a closure could also be provided if desirable as demonstrated by the flame library.
3. Capturing is done into 1 ring ring buffer shared between threads (1 per process).  This implies the need for locking at every record site.  For now I think this will be OK as it simplifies the design greatly (can have a global per-process limit for collection hit in terms of RAM & it's easy to iterate/dump whereas traversing TLS data structures requires more work) & shouldn't be an issue until there are a lot of threads generating a lot of trace data.
4. It's off by default.  You have to call `xi_perf::start()` to actually have the perf calls record anything.  Otherwise they're not recorded.  Similarly, there's a `xi_perf::stop()` which stops collection.  Start/stop simply set a global atomic boolean that's checked in each function. 
 `xi_perf::clear()` in case it conflicts with performance improvements in the future.

**Comment by cmyr** [comment]
Sounds great. My only note is that in xi-mac we're currently enabled by default; at least in the short term this at least saves us an RPC, and lets us write a trace if/when we see performance problems, instead of having to start a trace and repro?

**Comment by vlovich** [comment]
I think that's how this would work.  These are all process-local API calls.  so you'd just call xi_perf::start() in the main/application startup of your process.

**Comment by raphlinus** [comment]
That sounds great. Some rough thoughts.

1. The ring buffer write itself is so cheap that I don't think there's much gain in disabling it - the atomic boolean read and branch have nonzero (though probably very very small) cost. That said, we might defer _allocating_ the ring buffer for the start, and that could save ram.

2. Most of the cost (measured at ~130ns) of the Swift version is the string. This leads to the question of what the string type should be. The easiest and most efficient is `'static &str`, but that leaves some flexibility on the table. [Into<Cow>](https://jwilm.io/blog/from-str-to-cow/) might be the win.

3. Agree locking is best, simplifies thing and the cost of the uncontended lock should be very low.

4. We might consider threading a request id. This is not done in the Swift version, but doing so might help greatly in automating statistics.

5. I like the guard idea!

**Comment by vlovich** [comment]
1. Well, you do have to acquire a lock which has a mixed bag in terms of performance cost (not as cheap as you would hope on OSX).  That being said, I agree it's *probably* not an issue in terms of runtime.  My thought was that the allocation of the buffer(s) would also be controlled by that too (I was originally thinking of using TLS buffers which would make it more difficult probably than I wanted for a v1 but now that I've settled on a shared buffer can certainly do that).

1. I think for v1 having a static string is probably best for now unless you really think it will have runtime-generated strings.  If we want to expand on having extra payload data attached, it might be best to separate that/provided a lazy printf mechanism.  Thoughts?

1. Uncontended cost of mutex acquisition on OSX was 200ns at one point.  Now this was improved a few years back but mutexes are simply not a big priority at Apple because the focus is on GCD for multithreading.  I haven't rerun the numbers recently.

1. Can you please elaborate on the request id?  Is this provided by the user? Automatically generated some how?

**Comment by raphlinus** [comment]
I think it makes sense to use an extra payload, and that could be Option<String> so it's very cheap in the common case.

There's no excellent request id right now, so I imagine it's something that would be added in the rpc framework. However, now that I think about it, it's a pretty nontrivial change (it requires additional fields for all the RPC methods), so let's put that on the table for now.

**Comment by vlovich** [comment]
Oh, I understand what you mean by request ID now.  I'll add in the extra Option<String>.  FWIW uncontested lock on my macbook pro running 10.13.2 is ~50ns.

**Comment by vlovich** [comment]
the trace API is ready for some feedback i think (this is just the API itself, not the dumping logic).  https://github.com/vlovich/xi-editor/tree/trace.

trace takes ~70ns +/-17, trace_block/trace_closure takes 100 +/- 28
time::precise_time_ns takes 31ns +/- 11 (2 of them which is what trace_block has takes 69 +/- 10)

instruments indicates for trace 44.7% is spent getting the time, 23.7% is spent acquiring & releasing the lock for the ring buffer, 6% is spent in "std::panicking::panicking" (presumably this is because i'm using the default unwrap panic handler? i don't have any panics AFAICT). i.e. 25.6% () is spent on actually inserting into the ring buffer.

for trace_block it's 58.2, 16.1, & 4.7 respectively (i.e. 11% is spent on actually inserting into the ring buffer).

The timestamp overhead I think is due to an suboptimal implementation of time::precise_time_ns.  I benchmarked the FFI overhead of mach_absolute_time at ~23ns.  If I make a call to mach_timebase_info I get similar results.  If mach_timebase_info can be cached rather than invoked each time, precise_time_ns should be ~25% faster.  Everything online, including reference Apple code, seems to indicate it can be.

**Comment by vlovich** [comment]
I sent the issue about precise_time_ns upstream as https://github.com/rust-lang-deprecated/time/issues/159.

**Comment by cmyr** [comment]
Okay, I took a quick look through and everything seems reasonable? There are some little nits and questions I'd have if this were a PR, but in terms of just focusing on the API this seems reasonable.

Perhaps my one Q is on the distinction between labels and payloads; I presume payload is for something like a 'note', that can be stored with the trace? In any case, I think it might make sense to use `StrCow` or the label as well; we could imagine wanting to dynamically generate the label from the method name of a received RPC or something. What do you think?

**Comment by vlovich** [comment]
Yes, payload is like a note associated with that sample.  It was requested by Raph.  I think it might make more sense to even just make it a hashmap/tuple instead to avoid callers having to serialize into a string.  That's more along the way of how os_trace_with_payload on OSX/iOS work (not serializing also means you can examine the payloads without parsing).

Let me benchmark the implication of switching to StrCow for the label.

Honestly, I don't yet understand Rust ownership/lifetime rules well enough to understand how Cow works (I copied StrCow from the flame thing).  What does the first template argument mean?  Does the Cow instance implicitly keep the underlying value alive even if other references drop?  Will changing the underlying value also be reflected in a borrowed Cow or will Rust rules prevent changing the original value?

**Comment by cmyr** [comment]
Payload: what might make the most sense is having the payload be one of `serde_json::Map` or `serde_json::Value`, since we're going to json in any case. I agree that a `Map` might be the more flexible option.

Cow: `Cow`s aren't reference counted; instead they can either own their data or borrow it per the normal borrow rules. The first template argument (the lifetime argument) refers to the lifetime in the borrow case. If it's `'static` it means that the `Cow<str>` will be either a `'static str` or the assoc type of the `ToOwned` trait of `str`, which is `String`. 

As you said, ownership rules mean you can't mutate the underlying value if it's been borrowed by the `Cow`; and if you need to mutate the `Cow` itself, (with `Cow::to_mut`) it will clone the underlying data if necessary.

What it really means for us is that with only minor overhead we can use `'static str`s in most places, but have the opportunity to use a runtime-generated `String` when it's useful.

**Comment by vlovich** [comment]
It looks like using a StrCow for the name has a ~20-40ns impact on my machine (16-30%).  It seems a bit high when you can shove that info into payload instead.  Thoughts?

**Comment by vlovich** [comment]
Benchmark results on my machine for more complex types of payload:

```
strcow payload:
test tests::bench_trace_block                               ... bench:         156 ns/iter (+/- 90)
test tests::bench_trace_block_disabled                      ... bench:          18 ns/iter (+/- 5)
test tests::bench_trace_block_payload                       ... bench:         135 ns/iter (+/- 76)
test tests::bench_trace_closure                             ... bench:         126 ns/iter (+/- 24)
test tests::bench_trace_closure_disabled                    ... bench:           3 ns/iter (+/- 1)
test tests::bench_trace_closure_payload                     ... bench:         120 ns/iter (+/- 59)
test tests::bench_trace_instant                             ... bench:          92 ns/iter (+/- 20)
test tests::bench_trace_instant_disabled                    ... bench:           2 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:          92 ns/iter (+/- 15)

json payload:
test tests::bench_trace_block                               ... bench:         140 ns/iter (+/- 7)
test tests::bench_trace_block_disabled                      ... bench:          16 ns/iter (+/- 2)
test tests::bench_trace_block_payload                       ... bench:         452 ns/iter (+/- 87)
test tests::bench_trace_closure                             ... bench:         139 ns/iter (+/- 14)
test tests::bench_trace_closure_disabled                    ... bench:           4 ns/iter (+/- 0)
test tests::bench_trace_closure_payload                     ... bench:         532 ns/iter (+/- 92)
test tests::bench_trace_instant                             ... bench:         103 ns/iter (+/- 15)
test tests::bench_trace_instant_disabled                    ... bench:           2 ns/iter (+/- 1)
test tests::bench_trace_instant_with_payload                ... bench:         449 ns/iter (+/- 125)

dict payload:
test tests::bench_trace_block                               ... bench:         143 ns/iter (+/- 26)
test tests::bench_trace_block_disabled                      ... bench:          15 ns/iter (+/- 8)
test tests::bench_trace_block_payload                       ... bench:         378 ns/iter (+/- 186)
test tests::bench_trace_closure                             ... bench:         129 ns/iter (+/- 19)
test tests::bench_trace_closure_disabled                    ... bench:           3 ns/iter (+/- 0)
test tests::bench_trace_closure_payload                     ... bench:         402 ns/iter (+/- 107)
test tests::bench_trace_instant                             ... bench:         110 ns/iter (+/- 21)
test tests::bench_trace_instant_disabled                    ... bench:           3 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:         373 ns/iter (+/- 68)
```

The most notable impact is on xi_trace::trace_payload().  It's quite possible that the code as written forces unnecessary copies which is where the pessimization comes from.  For now, I've simply parameterized what the payload type is behind feature flags (string by default but can pass dict_payload or json_payload to choose those backends).

**Comment by vlovich** [comment]
I'll try to come up with some fairer examples.  I'm not sure what the performance of format! is like, but I suspect it's not fair either as there's more to it than just copying some extra bytes around.  Let me write up some additional benchmarks.

**Comment by vlovich** [comment]
Here's the performance of calling .to_string()
```
test tests::bench_trace_block                               ... bench:         131 ns/iter (+/- 26)
test tests::bench_trace_block_disabled                      ... bench:          18 ns/iter (+/- 3)
test tests::bench_trace_block_payload                       ... bench:         204 ns/iter (+/- 81)
test tests::bench_trace_closure                             ... bench:         132 ns/iter (+/- 27)
test tests::bench_trace_closure_disabled                    ... bench:           4 ns/iter (+/- 0)
test tests::bench_trace_closure_payload                     ... bench:         203 ns/iter (+/- 39)
test tests::bench_trace_instant                             ... bench:          95 ns/iter (+/- 18)
test tests::bench_trace_instant_disabled                    ... bench:           3 ns/iter (+/- 1)
test tests::bench_trace_instant_with_payload                ... bench:         179 ns/iter (+/- 32)
```

So it looks like it's still 2x faster (at least for trace_closure_payload).

`format!("value = {}", value)`:
```
test tests::bench_trace_block                               ... bench:         140 ns/iter (+/- 24)
test tests::bench_trace_block_disabled                      ... bench:          15 ns/iter (+/- 5)
test tests::bench_trace_block_payload                       ... bench:         289 ns/iter (+/- 30)
test tests::bench_trace_closure                             ... bench:         120 ns/iter (+/- 60)
test tests::bench_trace_closure_disabled                    ... bench:           3 ns/iter (+/- 1)
test tests::bench_trace_closure_payload                     ... bench:         292 ns/iter (+/- 64)
test tests::bench_trace_instant                             ... bench:          90 ns/iter (+/- 65)
test tests::bench_trace_instant_disabled                    ... bench:           3 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:         269 ns/iter (+/- 59)
```

Still ~2x faster.

Changing dictionary to have a copy of the incoming string 
`d.insert(StrCow::from("test"), StrCow::from(value.to_string()));`:
```
test tests::bench_trace_block                               ... bench:         145 ns/iter (+/- 75)
test tests::bench_trace_block_disabled                      ... bench:          16 ns/iter (+/- 9)
test tests::bench_trace_block_payload                       ... bench:         472 ns/iter (+/- 176)
test tests::bench_trace_closure                             ... bench:         137 ns/iter (+/- 25)
test tests::bench_trace_closure_disabled                    ... bench:           4 ns/iter (+/- 2)
test tests::bench_trace_closure_payload                     ... bench:         472 ns/iter (+/- 358)
test tests::bench_trace_instant                             ... bench:         110 ns/iter (+/- 17)
test tests::bench_trace_instant_disabled                    ... bench:           3 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:         429 ns/iter (+/- 286)
```

So it looks like 17% slower.  The large variance makes me a little nervous, but the same mean value is reported consistently across runs so I'm inclined to believe it.

json to `json!({"test": value.to_string()})`:
```
test tests::bench_trace_block                               ... bench:         147 ns/iter (+/- 39)
test tests::bench_trace_block_disabled                      ... bench:          17 ns/iter (+/- 5)
test tests::bench_trace_block_payload                       ... bench:         526 ns/iter (+/- 115)
test tests::bench_trace_closure                             ... bench:         134 ns/iter (+/- 60)
test tests::bench_trace_closure_disabled                    ... bench:           3 ns/iter (+/- 2)
test tests::bench_trace_closure_payload                     ... bench:         529 ns/iter (+/- 254)
test tests::bench_trace_instant                             ... bench:         109 ns/iter (+/- 22)
test tests::bench_trace_instant_disabled                    ... bench:           3 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:         504 ns/iter (+/- 101)
```

This one looks to be more of a wash (but still slower than dict & much slower than string).  Probably constructing the object graph is more expensive than any string copy.

**Comment by cmyr** [comment]
my results for using `StrCow` for name:

before:
```
test tests::bench_trace_block                               ... bench:         109 ns/iter (+/- 5)
test tests::bench_trace_block_disabled                      ... bench:          17 ns/iter (+/- 0)
test tests::bench_trace_block_payload                       ... bench:         102 ns/iter (+/- 8)
test tests::bench_trace_closure                             ... bench:          94 ns/iter (+/- 4)
test tests::bench_trace_closure_disabled                    ... bench:           3 ns/iter (+/- 0)
test tests::bench_trace_closure_payload                     ... bench:          95 ns/iter (+/- 5)
test tests::bench_trace_instant                             ... bench:          73 ns/iter (+/- 2)
test tests::bench_trace_instant_disabled                    ... bench:           1 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:          70 ns/iter (+/- 3)
```

after:
```
test tests::bench_trace_block                               ... bench:         110 ns/iter (+/- 0)
test tests::bench_trace_block_disabled                      ... bench:          15 ns/iter (+/- 0)
test tests::bench_trace_block_payload                       ... bench:         103 ns/iter (+/- 8)
test tests::bench_trace_closure                             ... bench:          97 ns/iter (+/- 7)
test tests::bench_trace_closure_disabled                    ... bench:           4 ns/iter (+/- 0)
test tests::bench_trace_closure_payload                     ... bench:         100 ns/iter (+/- 4)
test tests::bench_trace_instant                             ... bench:          69 ns/iter (+/- 8)
test tests::bench_trace_instant_disabled                    ... bench:           1 ns/iter (+/- 0)
test tests::bench_trace_instant_with_payload                ... bench:          71 ns/iter (+/- 1)
```
