### ISSUE TITLE
use case: language server API client

### ISSUE THREAD

**Issue by andrewrk** [google/xi-editor#473]
I am here to present a use case for Xi and ask if this use case is in scope for Xi.

I am working on a new programming language called [Zig](http://ziglang.org/) (pronounced "Zigh"). I currently use vim to edit source code, and I have a simple syntax highlighting file, but don't have access to any code completion or refactoring tools.

Use case: the Zig compiler could act as a server for Xi. Xi defines some kind of API protocol, and as long as the language server fulfills this API, Xi supports syntax highlighting, AST-aware transformations, code completions, and all the fancy refactoring tools you would expect from an IDE.

Even fledgling languages could have advanced IDE support, provided they fulfilled this API.

Here's an existing protocol: http://langserver.org/
However, one could pick this or perhaps invent a new and even better standard.

P.S. I'm RSVP'd to your [localhost](https://www.recurse.com/events/localhost-raph-levien) talk on Xi, so I hope to talk to you then.

**Comment by cmyr** [comment]
LSP support is definitely in our long-term plans, but is probably a ways out; but it has been an active reference when thinking about plugin support. So yes, but not for a while.

I'm also not sure about using the LSP for syntax highlighting; I didn't know this was part of its mandate. I'd be curious about performance.

**Comment by andrewrk** [comment]
For syntax highlighting, it makes sense to have some kind of way to specify syntax highlighting, not necessarily having the server do it. The reason to have it as part of the protocol would be just so that there is a single canonical point of information about how to describe a language, even if that particular server endpoint is just to return a pre-built structure describing the syntax in some abstract way.

**Comment by cmyr** [comment]
Yea, the ergonomics are certainly nice. Our current approach _is_ to delegate syntax highlighting (and other language specific things) to plugins; currently we have a single plugin based on [syntect](https://github.com/trishume/syntect) that handles highlighting using the [sublime-syntax](http://docs.sublimetext.info/en/latest/reference/syntaxdefs.html) format. We don't currently support adding new syntax defs, but that wouldn't be too tricky.

We also have the idea that there may be high throughput parsers available for particular languages, that would provide better/faster syntax highlighting; there's a sketch of this idea in the `rust/experimental/lang` directory.

In any case, it should be very possible at some future point for you to write a single plugin that provided support for syntax highlighting, indentation, and other language-specific features. :)

**Comment by njskalski** [comment]
@cmyr and if someone wanted to integrate LSP, how would you suggest to approach it? Integrate it with backend? Frontend?

**Comment by mqzry** [comment]
It should be written as a plugin. See https://google.github.io/xi-editor/docs/plugin.html and https://google.github.io/xi-editor/gsoc.html#language-server-plugin.

The whole thing boils down to implementing a mapping the JSON-RPC of the language server protocol to the plugin JSON-RPC of xi. There will be a lot of things that are not supported by xi. What exactly should be added and how is the non-trivial part.

**Comment by cmyr** [comment]
I'll also add that as part of GSoC, @betterclever will be working on LSP support.

**Comment by jansol** [comment]
Implementation is being tracked in #659. This can probably be closed?

**Comment by cmyr** [comment]
👍
