### ISSUE TITLE
Issue while building project. 

### ISSUE THREAD

**Issue by ERbittuu** [google/xi-editor#474]
error: failed to run custom build command for `onig_sys v65.0.1`

**Comment by ERbittuu** [comment]
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Compiling onig_sys v65.0.1
   Compiling serde_derive v1.0.15
   Compiling libflate v0.1.12
   Compiling plist v0.2.3
error: failed to run custom build command for `onig_sys v65.0.1`
process didn't exit successfully: `/Users/utsav.patel/Desktop/xi-mac/xi-editor/rust/syntect-plugin/target/debug/build/onig_sys-2fbc6b24ccdd0a94/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/Users/utsav.patel/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-65.0.1/oniguruma" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_INSTALL_PREFIX=/Users/utsav.patel/Desktop/xi-mac/xi-editor/rust/syntect-plugin/target/x86_64-apple-darwin/debug/build/onig_sys-8ae3957518f21c8b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /Users/utsav.patel/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.26/src/lib.rs:599:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by cmyr** [comment]
@ERbittuu is `cmake` not installed? Double check the [requirements](https://github.com/google/xi-mac#requirements), it's possible we're missing something...
