### ISSUE TITLE
Syntect plugin shouldn't send an update for autoindent if the previous line is blank

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#492]
Currently we check if the preceding line only contained whitespace, but the empty string passes this test. We should not send an update in the empty string case.

Related to, (but not necessarily the cause of?) https://github.com/google/xi-mac/issues/115

Anyone interested in taking a stab at this it should be a pretty quick fix in [rust/syntect-plugin/src/main.rs](https://github.com/google/xi-editor/blob/master/rust/syntect-plugin/src/main.rs)

**Comment by vlovich** [comment]
Regarding your repro you said you were unable to reproduce, FWIW I'm running debug xi-mac.

 xi-editor 0dcb03db053c387326c3c0bccfd63f9c340a96b3 (my FFI branch) which is 2 commits ahead of 89d122347cbb41f54073169f20443b8faf7b6b8d.

For xi-mac I'm on cc43001c58c761b7fe4af48d8bcc0c6c98347ad9 which is 1 commit ahead of 17fbf4ee8c33b00e62adb3e39b8596ee3e84813c.

**Comment by cmyr** [comment]
Okay, thanks. I'm going to be pretty busy through early next week, so might not be able to follow up much myself but I'll check in on the issues/irc a couple times a day.

**Comment by MaxfieldLewin** [comment]
Hi, I'd be interested in taking a stab at this if nobody else is

**Comment by cmyr** [comment]
@MaxfieldLewin sure!

**Comment by vlovich** [comment]
I'm also not 100% sure the assumption is correct.  It works for C-based languages that don't assign meaning to whitespace but other languages (python, brainfuck, etc) do.

**Comment by cmyr** [comment]
@vlovich agree in the general case, but this is specifically about _matching_ existing indentation; in the case of no indentation, this doesn't require an update, but we're actually sending an update containing the empty string.

**Comment by vlovich** [comment]
That makes sense I guess.  It would also be great to see a trace diff
before and after for the perf improvement.

**Comment by jorge-jbs** [comment]
Is it ok if a work on this? I think I have a solution but I can't test it because I am not able to compile the syntect plugin.

**Comment by MaxfieldLewin** [comment]
@jorge-jbs go for it, I have not made any progress

**Comment by cmyr** [comment]
@jorge-jbs What's your issue with the syntect plugin? Building syntect does require `cmake`, iirc.

**Comment by jorge-jbs** [comment]
@cmyr That was the exact problem I was having! It was late at night so I didn't notice but this morning I got it fixed. Now I'm struggling making xi-tui actually show syntax highlighting.

**Comment by cmyr** [comment]
@jorge-jbs cool. I haven't tried the tui client in quite a long time, so can't offer too much help there, but maybe this? https://github.com/little-dude/xi-tui/issues/47
