### ISSUE TITLE
Include line numbers when updating plugins

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#496]
I thought there was an issue for this, but I'm not sure where it is. 😕 This is the next component of #466, and so something I will eventually be blocked on. There's currently an issue #184 around the need to include line numbers when updating the client; something similar is also needed for updating plugins.

There is also possibly a larger issue here around what exactly the distinction is  between a client/peer/plugin, and what room there is there for code reuse; something I want to mention but not focus on in this issue.

In any case: we need to make it possible for the plugin _host_ to efficiently find a given line that may or may not exist in its cache. This means knowing how many lines exist in any chunks of document that might be absent from the cache, and possible also knowing either the offsets of linebreaks that are not in the cache or some subset of these offsets, so that we can efficiently fetch the chunk of document containing the line we need, as needed.

This is made a little trickier because unlike with the client, core does not know the contents of a given plugin's cache.

The thing which makes the most immediate sense to me, at this instance, is that the plugin has some list of line numbers and their offsets, which can be kept up to date as deltas are applied; plugin updates would also include some sort of delta against this structure. The list could either be complete or else have an entry for every nth line. 

I'm curious to hear if there might be a better approach?

**Comment by vhodges** [comment]
@cmyr #333 is the other issue.

**Comment by cmyr** [comment]
@vhodges Ah thanks, not sure how I missed that. WIll keep this issue, I think it's a bit more fleshed out.

**Comment by cmyr** [comment]
This is addressed in #568.
