### ISSUE TITLE
Compilation errors when building with xcode

### ISSUE THREAD

**Issue by shikloshi** [google/xi-editor#5]
I'm trying to build xi-editor and getting this: 
```rope/src/lib.rs:454:33: 454:41 error: use of unstable library feature 'convert': waiting on RFC revision (see issue #27729)```

```rope/src/lib.rs:454:46: 454:54 error: use of unstable library feature 'convert': waiting on RFC revision (see issue #27729)```

```rope/src/lib.rs:1060:75: 1060:83 error: use of unstable library feature 'convert': waiting on RFC revision (see issue #27729)```

I just cloned the project and run ```open XiEditor.xcodeproj``` and hit Run. 
What am I doing wrong?

**Comment by zyanho** [comment]
you must use beta or nightly version of rust to build this.

**Comment by raphlinus** [comment]
No, I'm building with stable, currently 1.8. What's your Rust version?

**Comment by shikloshi** [comment]
Yes, the problem was that I tried building with rust 1.4.0 once I upgraded it to 1.8.0 it worked. Thanks.
