### ISSUE TITLE
Consider stdin/stdout as an alternate (slimmer) comms channel for Xi collaborators

### ISSUE THREAD

**Issue by paul-hammant** [google/xi-editor#500]
A feature request not a bug.

Firefox's WebExtension's native conduit is the example to understand here. They've an example in Python, and I made one in Rust (or paid for it to be made really) - https://github.com/paul-hammant/EditThisPage_WebExtension. Amusingly I've a Python test harness for that Rust implementation in that repo too. 

On the Api?  It's fairly open - you post a message length then a message to stdout, and the other process reads a size and a payload from stdin. No prizes for working out how replies go back. With something like BEEP you could make that full-duplex if you needed that.

This alternate API would be for small plugins where it is OK to spawn a process in advance of chatting to it via stdin/stdout.

**Comment by cmyr** [comment]
To make sure I understand, when you say 'collaborators' are you thinking of plugins? Plugins _do_ currently run as processes, and communicate with xi-core over stdin/stdout, using a protocol based on json-rpc. Could you perhaps clarify the distinction you're making?

**Comment by paul-hammant** [comment]
Ahh sorry - I thought you were listening on a socket (per conventional web servers). You're already doing what I'm suggesting - ignore me.
