### ISSUE TITLE
Incorrect handling of BOM

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#506]
We currently fail to properly handle utf-8 which includes a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). This is valid utf-8, and should be handled correctly.

There's probably a meta-issue here around supporting different encodings. Our internal representation will always be utf-8, but we may want to convert from/to another format when reading and writing; and we may want to allow the user to specify a desired encoding.

My longer term vision of this is that the `Editor` type has a new member, `encoding`, which will be an instance of some `CharacterEncoding` enum. Initially this will have two members, `Utf8` and `Utf8WithBom`. When we read a file, we check for the presence of the BOM (the first three bytes being `ef bb bf`); if it's present we strip it, and assign the appropriate enum member. When writing to disk, we pass the enum with the text to write, and switch on it to determine behaviour.

xi-mac issue: https://github.com/google/xi-mac/issues/125

**Comment by wuweiweiwu** [comment]
@cmyr can I work on this? :)

**Comment by cmyr** [comment]
@wuweiweiwu absolutely. If you have any questions, you can ask them here or in the IRC. :)

**Comment by wuweiweiwu** [comment]
@cmyr will do! Thanks!

**Comment by ed359** [comment]
Sorry @wuweiweiwu, I'd already done this PR which implements in its most basic form the UTF8 BOM support @cmyr mentions here. 

It might be fun to extend this to support a wide variety of encodings, that's a much bigger job!

**Comment by cmyr** [comment]
Fixed in #513. @wuweiweiwu sorry, very happy to find you something else though!

**Comment by wuweiweiwu** [comment]
@cmyr That would be awesome! Is there anything you would recommend for someone beginning in Rust?

**Comment by cmyr** [comment]
@wuweiweiwu #444 might be a reasonable first issue? As raph mentions there, the project would be to move to a more abstract 'gesture' api, instead of talking about clicks specifically. This has been implemented in the case of cmd+click, which the frontend sends as a 'toggle selection gesture'. 

Alternatively, #434 is quite contained.

**Comment by wuweiweiwu** [comment]
@cmyr Sounds good! I'd love to take #444
