### ISSUE TITLE
What's the command for scroll one line?

### ISSUE THREAD

**Issue by dzhou121** [google/xi-editor#518]
I can see ```scroll_page_down``` and ```scroll_page_up``` to scroll one page up/down. But's I couldn't find API to only scroll one line? (ctrl-e, ctrl-y in vim)

**Comment by cmyr** [comment]
@dzhou121 I don't believe this exists explicitly; however the `scroll` command lets you pass an arbitrary line range. We have (very loose) plans to simplify the movement commands so there's a single `movement` rpc that has a parameter describing the movement type, like `page_up / line_down`; possibly `scroll` should be changed to work similarly?
