### ISSUE TITLE
Goto negative line makes editor unresponsive

### ISSUE THREAD

**Issue by scholtzan** [google/xi-editor#531]
If I enter a negative number in "Goto Line" in xi-mac then the editor becomes unresponsive and exits with the following error:
```
xi-core exited with error:
UnknownRequest(ErrorImpl { code: Message("invalid value: integer `-13`, expected u64"), line: 0, column: 0 })
```
In order to prevent this, should xi-mac simply prevent sending negative numbers? Or should there be some error handling in the xi-core?

**Comment by cmyr** [comment]
We made the perhaps questionable decision a while back to have core crash on illegal input. Given that, though, I think the frontend should be validating that text field before sending the RPC.
