### ISSUE TITLE
Crash on "new_view" request

### ISSUE THREAD

**Issue by little-dude** [google/xi-editor#554]
- OS / platform ArchLinux (kernel 4.15.8) 
- rust compiler version: `rustc 1.26.0-nightly (2789b067d 2018-03-06)`
- rust compiler installation method: rustup
- the frontend you're using: none, just spawning `xi-core` manually
- the commit you're on: 715f629f96028f8bba0be4cabf46c6e0c076b61d
- a full backtrace or error message, if available:

```
~/r/xi-tui ❯❯❯ xi-core                                                                              
{"id":1,"method":"new_view","params":{"file_path":"README.md"}} 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: xi_core_lib::internal::tabs::Documents::handle_request
  10: <xi_core_lib::MainState as xi_rpc::Handler>::handle_request
  11: crossbeam::scoped::scope
  12: <xi_rpc::RpcLoop<W>>::mainloop
  13: xi_core::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  18: std::rt::lang_start
  19: __libc_start_main
  20: _start
```

**Comment by little-dude** [comment]
how did you get the full stacktrace?

**Comment by dsp** [comment]
On MacOS: `RUST_TRACEBACK=1 target/debug/xi-core`

**Comment by little-dude** [comment]
aah. I do `cargo install --force` which compiles in release mode, so that may be the reason I don't have the full stacktrace.

**Comment by dsp** [comment]
From `git annotate` the code was introduced in a4a8620ac. I verified that `git co a4a8620ac~1 && cargo build && RUST_TRACEBACK=1 target/debug/xi-core` resulted in 

```
{"id":1,"method":"new_view","params":{"file_path":"README.md"}}
{"id":1,"result":"view-id-1"}
{"method":"available_plugins","params":{"plugins":[],"view_id":"view-id-1"}}
starting plugins for view-id-1
{"method":"config_changed","params":{"changes":{"auto_indent":false,"font_face":"InconsolataGo","font_size":14,"line_ending":"\n","plugin_search_path":[],"scroll_past_end":false,"tab_size":4,"translate_tabs_to_spaces":true,"use_tab_stops":true,"wrap_width":0},"view_id":"view-id-1"}}
{"method":"update","params":{"update":{"ops":[{"lines":[{"cursor":[0],"styles":[],"text":""}],"n":1,"op":"ins"}],"pristine":true},"view_id":"view-id-1"}}
{"method":"scroll_to","params":{"col":0,"line":0,"view_id":"view-id-1"}}
```

As expected. I am waiting for @cmyr response, but I assume this is a regression and we want to only use file_watchers when initiated.

**Comment by little-dude** [comment]
Thanks @dsp !

**Comment by cmyr** [comment]
@dsp's conclusion is correct; xi-core assumes that the client sends `client_started` on launch. This may not be well documented. I agree that erroring if something comes in before `client_started` would be good. Simplest improvement right now would be to have that `unwrap` be an `expect` explaining the error.

**Comment by little-dude** [comment]
@cmyr is that call mandatory? I'll add it to `xrl` and `xi-term`.

**Comment by cmyr** [comment]
@little-dude yes, it's mandatory. Currently only used for config stuff, but it will be an opportunity for core to do a variety of client-specific setup.

**Comment by cmyr** [comment]
My current feeling is that this is a documentation issue, for which I've opened #555. It does feel bad that core doesn't just exit with an error immediately if it receives an RPC before `client_started`?  This doesn't feel _great_.

@little-dude Feel free to close this if you're satisfied, otherwise happy to hear any thoughts you have.

**Comment by little-dude** [comment]
I agree that documentating the existing RPC a little better would be nice. I haven't touched `xi-term` for a few months, and in the meantimes, tons of new APIs have been added but I don't really know which ones are important, or what they do.

Don't feel bad for the core crashing. A clean exit or a crash has the same effect from the frontend perspective: the core is gone :) I think frontends should be able to detect when the core exited and handle it correctly. Currently, `xi-term` just hangs, which is bad.

Thanks a lot for your help and quick responses on this issue, `xi-term` is now fixed!
