### ISSUE TITLE
line_of_offset / offset_of_line should handle invalid inputs

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#563]
currently `offset_of_line` returns the offset of the end of the rope in any case where the argument is > the number of lines; and `line_of_offset` will panic if the argument is > the total number of bytes in the rope.

The panic is bad. The other result is arguably okay, but I suspect we want to have both these methods return `Option<usize>`. If we really want to insist on the current signatures, we should better document the current behaviour.

**Comment by raphlinus** [comment]
These are good questions. I've semi-deliberately tried to make these low-level functions strict, as invalid inputs are often an indication of logic error elsewhere. That said, I'm not being consistent here. Thinking about it, returning `Option` in both cases is definitely most Rust-idiomatic. Callers that know their inputs are valid can call `unwrap` (though I think too much unwrap is not a good thing), and callers that deal with potentially invalid inputs (especially queries from plugins and front-end) can use the Option as part of their error recovery.

Note that `offset_of_line` has a special case where the argument can be the number of newlines plus 1, in which returning the number of bytes is correct. This explains why the handling is the way it is; I combined giving _some_ result for invalid input with handling of this case.

**Comment by cmyr** [comment]
I don't mind being strict, as long as we document that inputs should be validated. I think if we're strict then we should also be crashing in `offset_of_line` if the argument is > num_lines + 1.

Counting lines is cheap but not free, so there's a possible argument against doing it every time this fn is called, if it might ever be called in a hot loop or something.

**Comment by raphlinus** [comment]
I'd probably lean towards strict, and agree on documenting the precondition. Agree that if we do this we need to fail on exceeding num_lines + 1.

Not sure why you're saying counting lines is not free, by my count it is.
