### ISSUE TITLE
Implement tabs in the UI

### ISSUE THREAD

**Issue by rtsuk** [google/xi-editor#57]
I've started work on this. The plan is to use an [NSSegmentedControl](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/SegmentedControl/Articles/SegmentedControlBasics.html) to display the tabs and an [NSTabView](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSTabView_Class/) to hold one EditView per tab.

**Comment by wezm** [comment]
Maybe consider [MMTabView](http://mimo42.github.io/MMTabBarView/) as well.

**Comment by rtsuk** [comment]
It looks good but I will have to check with @raphlinus on whether he wants to use something like that here.

**Comment by raphlinus** [comment]
MMTabView looks _really_ nice. I especially like the tear-off tab functionality, as I use that all the time. The license is compatible, and it looks like it would be quite a bit of work to duplicate what it already provides.

I don't think there's any good way to declare a reference to it and have Xcode resolve it the way that gradle or cargo would (correct me if I'm wrong), so probably the best way to get this dependency added is to copy it in under a third_party directory.

Some very minor polish issues: the "dirty" close buttons are lacking `@2x` (retina) PNGs, and some of the tab-reorder animations could be a little smoother. I'm sure both can be readily patched.

**Comment by rtsuk** [comment]
There's CocoaPods, but I don't think MMTabView is hosted there and I've never used CocoaPods.

I will experiment with MMTabView. Thanks @wezm!

**Comment by raphlinus** [comment]
So Sierra is out and has tabs built in. Things work to some extent without any code changes, although windows open by default to new windows, so getting to tabs is not very discoverable (there's a "Merge All Windows" added to the Window method).

I think the app delegate needs to implement newWindowForTab to get the "+" button, but that's easy enough.

Should the app window controller have its tabbing mode set to preferred? That would more or less match the Sublime behavior, but I'm not sure it follows the macOS recommendations. Also, I'm not sure how easy it will be to get a side bar (see #78) with tabs.
