### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by disordinary** [google/xi-editor#58]
I'm wondering what the thinking is on word wrapping? 

Forgive me if I'm wrong but the current implementation has the client sending the key code of a navigation key to the backend which figures out where the cursor sits. If you implement word wrapping this would necessitate the backend knowing the size of the viewport and also the size of each glyph for non monospaced fonts.

**Comment by raphlinus** [comment]
Yes, I've been thinking about that and it's in line with my thinking.

A rough sketch of my thinking. First you do what I'm calling a "difficulty analysis" to determine whether the monospace font assumption is valid. This is based on the font and the Unicode values in the text (the difficulty analysis will report multiple other bits, including bidi, complex script shaping, tab characters, etc).

If the monospace assumption is not valid, then the core maintains a cache of words. For misses, the core sends an RPC to the front-end with an array of words, and gets back the array of corresponding widths. (The RPC will also need to include font info for rich text styling).

So this won't be trivial, but seems pretty doable.

**Comment by Sineaggi** [comment]
How does emacs handle fonts? Afaik, the default page rendered for emacs contains an image, a few differently colored texts, as well as some italics and bold.

**Comment by raphlinus** [comment]
@Sineaggi I don't know much about emacs internals (I do know quite a bit about some other text systems). Colors are already partially supported, font styles are coming. I'm not planning on supporting images any time soon, as I think that increases the scope way beyond what's needed to build a great text editor.

**Comment by disordinary** [comment]
Rather than requesting the width of entire words would it not be better to request the widths of the individual characters used and build up the words as required? I realise that an entire unicode character set would be quite large but only a fraction would be used within any one document. You could probably make the assumption that the front end sends through the entire ascii set on load, and then additional unicode characters on demand, then there would be fewer needs for RPC calls and much more flexibility.

**Comment by raphlinus** [comment]
@disordinary The width of a word is only approximately the sum of the width of its individual characters, and that breaks down more and more as you get into complex scripts. For some cases (monospace font, CJK in the common case) you can do that more simply, but even ASCII in a real font has kerning and ligatures. So it needs to be done at word granularity. My experience suggests that caching effectiveness will be quite good.

**Comment by Sineaggi** [comment]
I've been playing around with vim, and it seems like they have an interesting method for supporting larger characters. Perhaps you've already seen this, but it was new to me.
For one, it looks like vim tries to hold closely to the single-width format. Symbols that are unknown, or are not known to be double width simply get cropped. Other symbols, such as Japanese character seem to be supported in a dual-width grid-like manner. It's also interesting to see that the cursor highlights only the first half of the character. Honestly? I have to say I like vim's design. It doesn't lend itself very well to an osx-style smooth-scrolling experience, but I guess it all depends on the final choice.

![neovim](https://cloud.githubusercontent.com/assets/889237/15314252/03175532-1bce-11e6-9d13-fe3c62a34582.png)
![neovim2](https://cloud.githubusercontent.com/assets/889237/15314253/031b9782-1bce-11e6-95c5-616ec811893a.png)

**Comment by raphlinus** [comment]
Personally not a fan of the cropping. It feels to me as much a limitation of NeoVim's ability to compute widths as a conscious design choice. Among other things, it mangles complex scripts like Hindi.
<img width="642" alt="screen shot 2016-05-17 at 6 55 23 am" src="https://cloud.githubusercontent.com/assets/242367/15324703/62c18f24-1bfc-11e6-987f-890f4ebc9043.png">

**Comment by Sineaggi** [comment]
True, I noticed the clipping in the various characters displayed in this [utf8 ](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt) test file I've been using.
Are you thinking about enforcing a single-double-triple-width format, where both ends communicated the width of a particular character or script, or are you leaning away from the mono-space assumption?

**Comment by raphlinus** [comment]
@Sineaggi leaning away from the assumption. I think it makes sense to assume it for characters covered by the monospace font. Latin-1 seems like a bare-minimum assumption; more Latin plus Greek and Cyrillic also seem useful, but Inconsolata doesn't support those, so I need to either extend the font, switch to something like Source Code Pro, or have a weak guarantee of monospace-ness.

Note that even for CJK, having the font set guarantee that the width of ideographs is exactly double the width of ASCII is not easy to enforce. It's pretty close for most of the fonts I've tested, but often not exact.

**Comment by Sineaggi** [comment]
Re that last bit, I'm not sure what you mean. If you rasterized all codepoints beforehand, and knew each of the character widths, and drew your gui on a grid with singular-double-triple widths, and let extra space fill in the gaps, then you wouldn't have to enforce anything.
Unless I'm misunderstanding your, which is probably the case here.

**Comment by disordinary** [comment]
That does restrict things though, if someone wants to code in comic sans why stop them? And yes I have seen it before. Most GUI text editors, as far as I know, do not restrict users to monospace.

Re: ligatures and kerning - I don't think most text rendering libraries would have an issue with either, you should be able to get bearing information. UI's that don't support getting all the information required to calculate the widths of words in the core engine should just enforce monospace fonts. 

The problem isn't just word wrapping, it's also being able to calculate where the cursor sits when pressing the up or down keys. If someone has a `very_long_verbose_and_descriptive_parameter_name_that_is_full_of_W_M_i_or_l_characters` for instance the ability for xi to calculate where to place the cursor accurately diminishes, not to mention multi lingual character sets as mentioned above.

It's a surprisingly complicated problem and well down the list, but it's worth thinking about.

**Comment by chriskrycho** [comment]
Also worth note that integration of ligatures and contextual alternates is increasingly valuable as typefaces like [Hasklig] and [Fira Code] become more popular. (I use Hasklig all day every day and going back to a non-ligatured typeface seems slightly barbaric. 😬) It's at the least worth making sure that any decisions made early on here don't block supporting that later, even if you don't support it out the gate. (Done properly, as in these typefaces, it shouldn't alter the width of any given line, which helps a bit for the monospaced typefaces.)

[Hasklig]: https://github.com/i-tu/Hasklig
[Fira Code]: https://github.com/tonsky/FiraCode

**Comment by jansol** [comment]
While word wrapping still has issues, those have their respective tracking issues so this can probably be closed?
