### ISSUE TITLE
Blank window after restoring from sleep

### ISSUE THREAD

**Issue by FilipMiletic** [google/xi-editor#580]
I left Xi open with some ~10k LOC file open. I closed the lid and put my MacBook in bag. After an hour when I opened the lid, Xi window was unresponsive and completely blank. Could be `xi-mac's` frontend bug, if so please move it.

Some additional info, just in case if needed:
- macOS 10.13.2
- rustc 1.24.1 (d3ae9a9e0 2018-02-27)
- rustup
- xi-mac
- `#b32254f0`

**Comment by cmyr** [comment]
Hmm, is there anything in the core crash logs? You can check them via 'Open Error Log Folder' in the debug menu.

**Comment by FilipMiletic** [comment]
Here is the log. First I thought it might be related to C syntax, but it's not, other files have the same problem. And It stays like that until I move the scroll or click. Even opening new tab and doing something in it doesn't seem to affect frozen state of problematic file.

`
Enabling tracing in core
error loading plugins from "/Users/phil/Library/Application Support/XiEditor/plugins", error:
Error { repr: Os { code: 2, message: "No such file or directory" } }
starting plugins for view-id-1
starting plugin at path "/Users/phil/Developer/other/xi-mac/build/Release/XiEditor.app/Contents/Resources/plugins/syntect/bin/xi-syntect-plugin"
starting plugin syntect
syntect using Plain Text
waiting on process 4632
process ended Ok(ExitStatus(ExitStatus(9)))
starting plugins for view-id-3
starting plugin at path "/Users/phil/Developer/other/xi-mac/build/Release/XiEditor.app/Contents/Resources/plugins/syntect/bin/xi-syntect-plugin"
starting plugin syntect
syntect using Plain Text
starting plugins for view-id-5
starting plugin at path "/Users/phil/Developer/other/xi-mac/build/Release/XiEditor.app/Contents/Resources/plugins/syntect/bin/xi-syntect-plugin"
starting plugin syntect
syntect using C
Event in open file Chmod("/Users/phil/Developer/other/zircon/kernel/kernel/event.c")
waiting on process 4634
process ended Ok(ExitStatus(ExitStatus(9)))
starting plugins for view-id-7
starting plugin at path "/Users/phil/Developer/other/xi-mac/build/Release/XiEditor.app/Contents/Resources/plugins/syntect/bin/xi-syntect-plugin"
starting plugin syntect
syntect using Plain Text
`

**Comment by cmyr** [comment]
@FilipMiletic Ah okay, so core hasn't crashed; it's just that the view isn't being rendered correctly. I'm not sure exactly what's going on, but this should be an issue in [xi-mac](https://github.com/google/xi-mac/issues). Would you like to reopen there?

**Comment by FilipMiletic** [comment]
I will, just want to reproduce it once again. Will report back shortly.

**Comment by FilipMiletic** [comment]
Okay, so it seems waking it up now didn't produce the problem. But what could be the problem (I'm stupid forgot to mention very important detail and that is) is that when I opened the lid when the problem occurred I was connected to external monitor (1080p Dell Monitor), so maybe that's the cause why the frontend blew up. I will try and reproduce that same situation when I get home tonight, and will reopen it on `xi-mac`. Sorry, it slipped my mind to mention that I was using external monitor. 😅

**Comment by vlovich** [comment]
Wouldn’t surprise me.  OS X has always struggled with external/multi
monitor support working properly.  Wouldn’t surprise me if our use of
OpenGL and layers for performance exposes some underlying bug we need to
work around.

**Comment by cmyr** [comment]
@FilipMiletic no sweat. I _suspect_ this may not be related to sleep and may be related to external monitors, although it may be a general bug. (I've seen this issue on my dev machine, which has an external monitor and never sleeps.)

**Comment by cmyr** [comment]
closing this, there's a related issue in xi-mac: https://github.com/google/xi-mac/issues/158
