### ISSUE TITLE
Minor ergonomics improvements around selections

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#589]
Breaking this out of some observations in #585. I think there are at least two little additions we could make to `Selection` and `SelRegion` to make them easier to work with:

- [ ] add a constructor (`fn new(..) -> Self`) to `SelRegion`.
- [ ] replace any existing `let _ = SelRegion { .. }` code with the new constructor
- [ ] add a constructor (`fn new_simple(..) -> Self`) to `Selection`, that constructs a `Selection` with a single region.
- [ ] use this constructor anytime a selection is created with a single region

Possibly, depending 

- [ ] refactor `view.rs`, so more code is shared between `select_word`, `select_line`  and (maybe) `toggle_sel`
- [ ] (maybe, depending on whether it would be useful; an exercise for the implementor) add an impl `From<SelRegion> for Selection`.  (only if this would make any of the logic in view.rs easier)

This is intended as a guideline, not as a concrete sketch. There may be other good options, or things I haven't thought of.

**Comment by YaLTeR** [comment]
I'd like to work on this.

**Comment by cmyr** [comment]
@YaLTeR sounds good, #585 is merged so this should be ready to go.
