### ISSUE TITLE
remove do_click, migrate to do_gesture

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#591]
I thought there was an existing issue for this, but apparently not?

mouse clicks were previously handled in `Editor::do_click`. We would like to move all mouse/touch related events into the the `do_gesture` method / RPC.

This involves adding new gesture types for the events currently handled by `do_click`, and handling the new events in `do_gesture`, with most of the code moving to `view.rs`. #585 is a good example of how gestures should work. Ideally a bunch of code can be shared between the various gesture types.

**Comment by scholtzan** [comment]
I will work on this.

**Comment by cmyr** [comment]
closed in #605
