### ISSUE TITLE
Selection affinity is incorrect when selecting lines via gesture

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#592]
Triple clicking on a line should select the whole line, but the affinity of that selection should be `Upstream`, e.g. the cursor should appear at the end of the selected line, not the beginning of the next one.

There are some other `TODO`s inline regarding affinity calculation; I don't know the story there, but @raphlinus can clarify.

**Comment by raphlinus** [comment]
If it's after the newline, then affinity won't help. I believe affinity should only make a difference for soft breaks, ie breaks introduced by line wrapping.

Incidentally, the behavior of triple-click is to put the cursor on the next line in both Sublime and VS Code. I'm not sure the existing behavior is wrong here.

**Comment by cmyr** [comment]
Hmm, okay. That feels strange to me, but I guess it's a natural consequence of including the line break in the line. I'll close this.
