### ISSUE TITLE
non-OS-X build instructions

### ISSUE THREAD

**Issue by neunenak** [google/xi-editor#6]
Can we get some text in a README about how to build and run a minimal version of the backend on non-OS-X platforms?

**Comment by Connorcpu** [comment]
It should definitely be added to the readme, but building the backend on non-OSX platforms is as straightforward as running `cargo build` in the `rust` directory. Assuming you have rust installed, of course.

**Comment by neunenak** [comment]
Sure, that's straightforward enough, but I"m having trouble figuring out how to actually use the rust backend by itself, and without being able to compile the entire working frontend + backend, it's hard to figure out what you might need to do to write your own frontend.

**Comment by raphlinus** [comment]
I added a little text to the README.

I definitely want to document the protocol, but am reluctant to spend too much time on it right now because it definitely will be changing (multiple windows, accurate invalidation, etc).

**Comment by Bluebird45** [comment]
It would be useful to have a list of which functions live in the back-end, which live in the front-end, and which haven't been implemented yet.

For example, to add keypad operations such as insert/overwrite, home, end, page-up, page-down, which are absent from the Linux front-end, xi_glium, am I right in assuming that the back-end is the place to patch those in?

**Comment by Sineaggi** [comment]
@Bluebird45 Some of those keypad functions already exist. The function `do_key` contains a switch statement that handles arrow keys, backspace, newlines, and the f1 key. And normal keys. The rest can be patched into that very same function.

**Comment by raphlinus** [comment]
The new documentation in [frontend.md](https://github.com/google/xi-editor/blob/master/doc/frontend.md) should be of interest to those following this issue.

**Comment by disordinary** [comment]
I was wondering if anyone was working on (or if there was an official) windows version that I could contribute to? I spend about 80% of my time as a windows dev at the moment and I have worked on custom text editor controls in the past. 

Also, while I applaud the idea of having native widgets, I was wondering if any thought was put to using a cross platform graphics library like skia for rendering the actual text? While windows and controls should use the native toolkit I don't see much benefit to using the native text drawing API's when there can be a gain in both consistency of rendering and also productivity by using a cross platform library.

**Comment by raphlinus** [comment]
@disordinary You might want to poke around @Sineaggi 's [XiEditorVS2015](https://github.com/Sineaggi/XiEditorVS2015). It's not official, but it looks like a start.

Regarding your other question, I'm open to doing my own text drawing _if_ I thought it could be done better than the native toolkit. On that, I'm skeptical, as native toolkits get to do lots of things like use hardware acceleration. For example, I'd like to see benchmarks of Skia text drawing compared with DirectWrite / Direct2D. It's also the case that doing our own drawing would bloat the front-end dramatically, pulling in lots of external dependencies, and I like the idea of it being lightweight.

**Comment by disordinary** [comment]
Thanks @raphlinus.

Re: skia I was mainly thinking about keeping api's consistent across platforms so that porting updates would be easier. The reality is that text rendering is such a basic function of an OS that they should all be feature compatible. Things get interesting if more graphical ways of displaying content and code are implemented one example being the minimap that sublime text uses.

**Comment by raphlinus** [comment]
Going to close this, as the README does explain how to build on non-OSX, and the documentation of the protocol is in reasonable shape considering it's still evolving. Improvements still welcome, of course.
