### ISSUE TITLE
`new_view` returns an error for non-existing file

### ISSUE THREAD

**Issue by eyelash** [google/xi-editor#627]
When sending a `new_view` request with a non-existing file as argument the core responds with a message like
```json
{"error":{"code":5,"message":"failed to load file"},"id":0}
```
which xi-gtk is not prepared to handle. I'm not sure if this is intended to be this way but I would prefer the core to just open a view and create the file on save. At the very least this behaviour is inconsistent with the [documentation](https://github.com/google/xi-editor/blob/master/docs/docs/frontend-protocol.md#new_view).

**Comment by cmyr** [comment]
Happy to just call this a bug, will patch soon.
