### ISSUE TITLE
Most edit methods print rpc with id=X not responded

### ISSUE THREAD

**Issue by mrandri19** [google/xi-editor#63]
## Reproducing
```bash
~/rustWorkspace/xi-editor/rust(master ✔) cargo run
     Running `target/debug/xicore`
{"id":1,"method":"new_tab","params":[]}
to core: {"id":1,"method":"new_tab","params":[]}
{"id":1,"result":"0"}
{"id":2,"method":"edit","params":{"method":"scroll","params":[0,43],"tab":"0"}}
to core: {"id":2,"method":"edit","params":{"method":"scroll","params":[0,43],"tab":"0"}}
rpc with id=2 not responded
```

## Why

When the `edit` method is called:
1. `handle_rpc` in `tabs.rs` is called
2. `do_edit` in `tabs.rs` is called
In `do_edit` if we provided some params respose is built:

```rust
let response = {
                if let Some(editor) = self.tabs.get_mut(tab) {
                    let method = params.get("method").unwrap().as_string().unwrap();
                    let params = params.get("params").unwrap();
                    editor.do_rpc(method, params)
                } else {
                    print_err!("tab not found: {}", tab);
                    None
                }
            };
```

response is either `None` or `editor.do_rpc(method, params)`

but `editor.do_rpc` is  `None` for all `async` edit methods
```rust
fn async(_: ()) -> Option<Value> {
    None
}
```
```rust
if let Some(response) = response {
                self.respond(response, id);
            } else if let Some(id) = id {
                print_err!("rpc with id={:?} not responded", id);
            }
```

## Solution
Remove the `print_err!("rpc with id={:?} not responded", id);` call.
I'll send a pull request.

**Comment by raphlinus** [comment]
What front-end are you using? The Swift one bundled in the repo does not have this problem. I think your actual problem is that your front-end is sending a sync RPC when it should be sending an async one. In that case, the error message is appropriate.

**Comment by mrandri19** [comment]
I'm using [xi_glium](https://github.com/potocpav/xi_glium) since I'm on linux. In its code for sending an async request it adds an id to the JSON object, which I believe it's the problem. Async requests don't have an id right?

**Comment by raphlinus** [comment]
Right, it shouldn't be sending an id on async requests. Right now, the only bad thing that happens is that error message, but that shouldn't be relied on.

**Comment by mrandri19** [comment]
Ok, thanks
