### ISSUE TITLE
flutter / fuchsia rich text editor

### ISSUE THREAD

**Issue by gedw99** [google/xi-editor#635]
Hey

I am interested in extending the flutter / dart code for rich text editor.
I cant seem to fin the actual front end code though for the fuchsia flutter code.
git clone https://fuchsia.googlesource.com/xi

I guess its not public ?

**Comment by raphlinus** [comment]
It's moved to https://fuchsia.googlesource.com/topaz/+/master/app/xi/ . Resolution of this issue would be to update the link. PR would be welcome :)

**Comment by gedw99** [comment]
even the links in the fuchsia repo are broken

services: FIDL service definitions. goes nowhere.. :)

**Comment by gedw99** [comment]
closing as i got this resolved

**Comment by gedw99** [comment]
Oh PR has not been pushed yet 
https://github.com/google/xi-editor/pull/636

**Comment by jansol** [comment]
Now it has.

**Comment by unordered** [comment]
The url <https://fuchsia.googlesource.com/topaz/+/master/app/xi/> is not found:

![not found screenshot](https://user-images.githubusercontent.com/21697340/68837198-0479c780-06f7-11ea-98ba-b531c13701b2.png)

**Comment by Ngo-The-Trung** [comment]
Seems like the implementation was removed in July from the googlesource website in commit 6ada2c0db1f9935f because it was unused.

This URL should work:
https://fuchsia.googlesource.com/topaz/+/4541ac62baa510ceef2e3d115adf90fd0af72447/bin/xi/
