### ISSUE TITLE
Add custom theme support

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#637]
This isn't super high priority but it's adjacent to some other things i'm looking at right now so wanted to add an issue in case someone is interested, it would be a fun little project.

Approximate work involved:

1. When the editor receives the `client_started` RPC, check if the `config_dir` argument is present; if it is, look for theme files in a `themes` subdirectory, and if any are present attempt to load them into the `ThemeSet` (owned by `ThemeStyleMap` in `styles.rs`).
2. sent the client the `available_themes` notification.
3. Ideally we would also use the file watcher to be notified on the fly if new themes are added; check how we do this already for config files.
4. Ensure that these loading operations show up in traces; see other uses of `trace_block` in the codebase.

Eventually we would also want to be caching binary dumps of all custom themes, so we can load them more quickly.

**Comment by virattara** [comment]
Interested!

**Comment by cmyr** [comment]
@virattara great, let me know if you have any questions!

**Comment by scholtzan** [comment]
This has been resolved in https://github.com/google/xi-editor/pull/675
