### ISSUE TITLE
Add #[must_use] annotation to SampleGuard

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#638]
Very small ergonomics improvement: with the new tracing infrastructure, the `SampleGuard` type should have the `#[must_use]` annotation; if you aren't keeping a reference to the returned guard than you should be using another trace method.

This is a one line change in `rust/trace/src/lib.rs`.

**Comment by zsilver1** [comment]
As a first time contributor, this seems like it's right up my alley.

**Comment by cmyr** [comment]
added in #656
