### ISSUE TITLE
Clarify initial client interaction with view

### ISSUE THREAD

**Issue by euclio** [google/xi-editor#640]
I'm trying to get a simple frontend up and running, and I'm confused over what RPCs should be sent when creating a new view. My current understanding is that after sending `client_started` on initialization, a frontend would typically call `new_view`, and then receive an update to the line cache for that view. 

The docs are unclear on what should happen next. Should my frontend attempt to render the view at this point? Should I then send an initial `scroll_to` to indicate to the core where the scroll window is?

Next, I'm confused as to what an "invalid" line means, and how a frontend should handle it. Does my client need to request that line so that the cache becomes valid? How can I do that?

It would be great to add these cases to the docs. I'd be happy to open a PR.

**Comment by cmyr** [comment]
Hey sorry for missing this issue!

Sending `scroll_to` is good practice although it isn't strictly necessary; if it isn't set core will assume that the view is at line 0 and has a height of 10 lines.

The view should render any time it receives either `update` or `scroll_to`.

The client shouldn't necessarily ever need to request lines, except in specific circumstances where it is prefetching lines for something like predictive scrolling. In the general case, core will send the necessary lines after a given edit/scroll event.

It's useful to think of the update protocol as being specifically about _cache_ state. An update message from core-> client should always leave the client with enough information to render the current view of the document.

The `invalidate` operation just tells the frontend to discard some set of lines. If those lines have been deleted, no further work is necessary; if those lines have been modified or replaced, then there will be an additional `insert` op that includes the new lines.

I agree that the frontend docs could use some help. Will take a look at that now.

**Comment by euclio** [comment]
Thanks for the clarification! So, to get the rest of the lines in the cache I need to send a `scroll` `edit`?

Also, I'm confused why I get `invalid` lines on the initial update. Is that just to let the cache know how many total lines are in the file, since the initial scroll window is only 10 lines?

**Comment by cmyr** [comment]
Yes, sending the `scroll` event will set the size of the viewport; and yes, the invalid lines on the first update inform the frontend of the total line count.

**Comment by cmyr** [comment]
closing this, docs were updated in #642 to discuss `client_started`.
