### ISSUE TITLE
Remove do_key from backend

### ISSUE THREAD

**Issue by ethan-tqa** [google/xi-editor#65]
I think it would be better that do_key is removed, and the backend is complete agnostic of key bindings. That way, porting to other platforms or keyboard layout or implementing modes (e.g. vim) will be easier. Further more, do_rpc currently cover pretty much all of the things that do_key does anyway.

**Comment by eyelash** [comment]
`do_key` was removed in ca1a03f4aeab96de6d2f36069ca17d922244fede. This bug can be closed now.
