### ISSUE TITLE
Display editor features in the README.

### ISSUE THREAD

**Issue by thekashifmalik** [google/xi-editor#668]
There is no description of any features on the Github page (README) or at https://google.github.io/xi-editor/.

Performance is mentioned, and granted that is a feature, but it might make sense to talk more about editor controls and other features instead of about its internal design. (That still has a place)

**Comment by Reificator** [comment]
With all due respect to the project authors and maintainers, there are no features yet.

Despite how often it makes it to the frontpage of HN, it's still in progress and very early at that.

When it's further along, I expect the various frontends will document their features, perhaps with a link back to a centralized featurelist.  But the core editor piece is likely to be advertised to developers, not end users.

**Comment by cmyr** [comment]
Yea, @Omar-Elrefaei pretty much nailed it; insofar as this is very much a work in progress, we're resistant to presenting it in such a way that would encourage people to actually use it as their editor. Basically: people are totally welcome to play around, but we don't want to present the idea that this is a text editor that you should consider for your day-to-day work (although I do use xi-mac quite a bit, though mostly just for markdown).

**Comment by thekashifmalik** [comment]
I see, that makes some sense. I guess this keeps making it to Hacker News so I assumed it was something people could start using.

Feel free to close the issue if it is not relevant for now.
