### ISSUE TITLE
build error: [E0015]: calls in constants are limited to struct and enum constructors   --> rpc/src/lib.rs:62:33

### ISSUE THREAD

**Issue by Z3TA** [google/xi-editor#669]
warning: unused `#[macro_use]` import
  --> trace-dump/src/lib.rs:33:1
   |
33 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0015]: calls in constants are limited to struct and enum constructors
  --> rpc/src/lib.rs:62:33
   |
62 | const MAX_IDLE_WAIT: Duration = Duration::from_millis(5);
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: a limited form of compile-time function evaluation is available on a nightly compiler via `const fn`
  --> rpc/src/lib.rs:62:33
   |
62 | const MAX_IDLE_WAIT: Duration = Duration::from_millis(5);
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `xi-rpc`.
warning: build failed, waiting for other jobs to finish...
error: build failed

$ uname -a
Linux zpc 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

$ rustc --version
rustc 1.24.1

Rust compiler installation method: rustup

$ git rev-parse HEAD
9be8aee72330d419e3316ea7873d054461f10a0f

$git log --pretty=format:'%h' -n 1
9be8aee

**Comment by scholtzan** [comment]
I encountered the same problem. You have to update to version 1.25.0 or higher. This version supports that `Duration::from_millis` can be used in a constant expression (https://github.com/rust-lang/rust/blob/master/RELEASES.md#stabilized-apis-1).

**Comment by Z3TA** [comment]
Thanks scholtzan!

I did nothing, and now rustc --version gives me:
rustc 1.26.0 (a77568041 2018-05-07)

Do rust auto update itself !? Should I be scared ? I am scared because so many things tend to break when updating. This is however my first time trying rust.

And now it builds!

**Comment by scholtzan** [comment]
Rust is not automatically updated (one way to update it, would be by running `rustup update`). But maybe you encountered a similar issue to this one: https://github.com/rust-lang-nursery/rustup.rs/issues/371 
Anyway, I am glad it is working for you now!
