### ISSUE TITLE
improve sample plugin's makefile

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#683]
It should be more like the syntect plugin's is: actually rebuilding on source changes, and installing correctly even if the target directory already exists.

**Comment by ajmalsiddiqui** [comment]
I'm a first timer and I'd like to take this one up. Is that alright? 
And is this the right place to ask for help/guidance if I get stuck?

**Comment by cmyr** [comment]
@ajmalsiddiqui it's all yours, and yes feel free to ask questions here. :)

**Comment by ajmalsiddiqui** [comment]
Awesome, thanks! 
Will make a WIP PR once I get to it. :)
