### ISSUE TITLE
Undo / redo

### ISSUE THREAD

**Issue by raphlinus** [google/xi-editor#69]
Implement Undo (⌘Z) and Redo (Shift-⌘Z) commands.

The undo buffer can be limited to, say, 20 deep, to keep the buffer sizes small and operations efficient.

It seems practical to implement it in terms of the [mini-CRDT](/google/xi-editor/blob/master/doc/crdt.md). The implementation should garbage collect undos that can no longer be toggled, either because they're older than the 20 or because a new edit happens on top of undone ones. The garbage collection can ideally happen after the update is sent back to the front-end or perhaps even done in an "idle task".

A sequence of inserts or backspaces should be merged into a single undo group.

For maximum UI polish, the menu items should be grayed out when undo or redo is not possible, and the string should be changed to indicate the nature of the edit. However, this is fairly advanced polish (and the strings will need to be localized in the general case), so not planning to do it any time soon.

I'm fairly close to a basic implementation, creating this issue to track remaining work.

**Comment by gnzlbg** [comment]
One of the things I like about emacs is unlimited undo, is it possible to do something like that without destroying performance?

An idea could be to serialize undos as deltas into a file. That way we could keep 20-40 undos in memory, and asynchronously every now an then append the oldest 20 back into a file. If the user gets to say undo number 20 out of 25 in the buffer we could speculatively fetch the next 10 undos from the file. 

If this "undo file" is memory mapped the whole approach could be made lag free.
