### ISSUE TITLE
crash when using selection for find

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#695]
Using <kbd>cmd</kbd>+<kbd>E</kbd> on xi-mac I get a crash when the selection is a caret.

There's a related issue where the search bar isn't correctly populated when the selection _isn't_ a caret.

@scholtzan maybe this is one for you?

**Comment by scholtzan** [comment]
I ignored <kbd>CMD</kbd> + <kbd>E</kbd> for now, but it is the next thing on my list.

**Comment by scholtzan** [comment]
This is fixed in https://github.com/google/xi-editor/pull/701 and can be closed.
