### ISSUE TITLE
core->client statusbar RPC methods should include the plugin id

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#702]
Currently there's no mechanism for a client to remove items when a plugin shuts down. Core already has access to the PluginId, so this should be threaded through to the client; the client can then handle it when it gets a `plugin_stopped` message.

@nangtrongvuon You want to take this? It would be nice to get it in before we really have anyone using this feature. It will also require a xi-mac companion, although I don't mind if we aren't handling the removal case yet, it's more important to have the protocol correct.

**Comment by nangtrongvuon** [comment]
Solved by #725. Can be closed now.
