### ISSUE TITLE
RPC for replace

### ISSUE THREAD

**Issue by scholtzan** [google/xi-editor#712]
# RPC for Replace

This is for discussing the RPC for replace. I imagine it to be quite similar to the find RPC, but perhaps a bit simpler.

## Actions related to replace

* Show replace bar with find: <kbd>⌥</kbd> + <kbd>⌘</kbd> + <kbd>F</kbd>
    * Filled with last replacement string 
* Replace next: <kbd>⌘</kbd> + <kbd>⌥</kbd> + <kbd>E</kbd>
    * If there is a selected occurrence: `[insert, find_next]`
    * No occurrence is selected: `find_next`
    * Option to preserve case: <kbd>⌘</kbd> + <kbd>⌥</kbd> + <kbd>A</kbd>
* Replace all: <kbd>^</kbd> + <kbd>⌥</kbd> + <kbd>return</kbd>
    * `[find_all, insert]`
* Use selection for replace: <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>E</kbd>
    * Always case insensitive

## Proposed RPC

```
replace { "chars": "n", "preserve_case": true }
replace_next { }
replace_all { }
selection_for_replace { }
replace_status { "chars": "n", "preserve_case": true }
```

* Replacement string and options are stored in the core similarly to find
* Replacement string and options get sent to the core while typing

**Comment by cmyr** [comment]
I'll admit I'm not super deep in find/replace land right now, but this sounds like a very good place to start. I think with some of this work it makes sense to get it working, and then we'll have a chance to play around more and see if we should refine.

**Comment by scholtzan** [comment]
Implemented in https://github.com/google/xi-editor/pull/720
