### ISSUE TITLE
backspace with translate_tabs_to_spaces should delete up to tab_width preceding spaces

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#716]
This was previously implemented (in #460) but broke somewhere along the way. That PR contains a good discussion of the motivation and ultimate design. Care should be taken not to regress on #714/#713. I'd like this to also include a test case in `event_context.rs`; doing this correctly might involve modifying the `ContextHarness` used for testing to allow it to be passed a custom config, which wasn't possible when that was first written.

As a bonus it would be great to also have a regression test for #713.

**Comment by nangtrongvuon** [comment]
I'm confused, I was going to take this issue but it seems the correct behavior is already there?

**Comment by cmyr** [comment]
Ah maybe this wasn't very well explained. Some examples, assuming `translate_tabs_to_spaces = true` and `tab_size = 4`:

- on a new line (not the first in the document), insert two spaces. Backspace should delete both.
- on a new line (not the first in the document) insert six spaces. Backspace should delete two.

Both of these are currently broken for me.

**Comment by nangtrongvuon** [comment]
Got it, going to work on this if I have time.
