### ISSUE TITLE
plugin refetching whole document on some inserts

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#721]
Not totally sure what's going on here but in a few trace files I've seen the plugin fetching the entire document in situations where that should not be necessary.

**Comment by raphlinus** [comment]
I'd check whether the "simple insert" test is failing. This can easily happen on transpose, insert when there is a selection, etc.

**Comment by cmyr** [comment]
Yes I remember encountering this a while ago when working on something else, and it seemed like that check might've been failing when an insert was at the end of the document. Would be a good place to start.

I'm going to mark this help wanted, and if someone is feeling adventurous I'd be happy to offer some more guidance.

**Comment by betterclever** [comment]
@cmyr Which plugin is showing this behaviour ? Is it the language plugin ?
