### ISSUE TITLE
Build failed on MacOS 10.13.4

### ISSUE THREAD

**Issue by BaldEagleX02** [google/xi-editor#729]
Build failed.
18 Errors
OS / platform: macOS 10.13.4)
rust compiler version: rustc 1.20.0 (f3d6973f4 2017-08-27)
rust compiler installation method: rustup
The commit you're on: a66bbd68037e392074ed69be5d3b84bc59c4ed44 - 926068d - #715 
A full backtrace or error message: 
Installing xi-core v0.2.0 (file:///Users/federico/Documents/xi-editor/rust)
 Downloading regex v1.0.0
 Downloading utf8-ranges v1.0.0
 Downloading regex-syntax v0.6.0
 Downloading thread_local v0.3.5
 Downloading aho-corasick v0.6.4
 Downloading ucd-util v0.1.1
 Downloading unreachable v1.0.0
 Downloading void v1.0.2
   Compiling num-traits v0.2.2
   Compiling bitflags v1.0.3
   Compiling utf8-ranges v1.0.0
   Compiling void v1.0.2
   Compiling unicode-xid v0.1.0
   Compiling bitflags v0.7.0
   Compiling dtoa v0.4.2
   Compiling crossbeam v0.3.2
   Compiling cc v1.0.15
   Compiling byteorder v1.2.2
   Compiling bytecount v0.3.1
   Compiling ucd-util v0.1.1
   Compiling same-file v1.0.2
   Compiling itoa v0.4.1
   Compiling adler32 v1.0.2
   Compiling unicode-segmentation v1.2.1
   Compiling serde v1.0.43
   Compiling plist v0.2.4
   Compiling build_const v0.2.1
   Compiling cfg-if v0.1.2
   Compiling libc v0.2.40
   Compiling safemem v0.2.0
   Compiling regex v1.0.0
   Compiling xi-unicode v0.1.0 (file:///Users/federico/Documents/xi-editor/rust/unicode)
   Compiling lazy_static v1.0.0
   Compiling xml-rs v0.7.0
   Compiling unreachable v1.0.0
   Compiling proc-macro2 v0.3.8
   Compiling num-integer v0.1.36
   Compiling walkdir v2.1.4
   Compiling regex-syntax v0.6.0
   Compiling crc v1.8.1
   Compiling base64 v0.8.0
   Compiling time v0.1.39
   Compiling filetime v0.1.15
   Compiling memchr v2.0.1
   Compiling miniz_oxide v0.1.2
   Compiling fsevent-sys v0.1.6
   Compiling thread_local v0.3.5
   Compiling miniz_oxide_c_api v0.1.2
   Compiling quote v0.5.2
   Compiling toml v0.4.6
   Compiling bincode v1.0.0
   Compiling serde_json v1.0.17
   Compiling aho-corasick v0.6.4
   Compiling fsevent v0.2.17
   Compiling chrono v0.4.2
   Compiling syn v0.13.4
   Compiling notify v4.0.3
   Compiling flate2 v1.0.1
   Compiling serde_derive_internals v0.23.1
   Compiling serde_derive v1.0.43
   Compiling xi-rope v0.2.0 (file:///Users/federico/Documents/xi-editor/rust/rope)
   Compiling syntect v2.0.1
   Compiling xi-trace v0.1.0 (file:///Users/federico/Documents/xi-editor/rust/trace)
error: use of unstable library feature 'ord_max_min' (see issue #25663)
   --> trace/src/fixed_lifo_deque.rs:182:47
    |
182 |             let overflow = self.storage.len().min(self.storage.len() + n_to_be_inserted - self.limit);
    |                                               ^^^

error: aborting due to previous error

error: Could not compile `xi-trace`.
warning: build failed, waiting for other jobs to finish...
error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:671:35
    |
671 |         let (mut l, mut offset) = self.get_leaf()?;
    |                                   ----------------
    |                                   |
    |                                   the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                   in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:671:35
    |
671 |         let (mut l, mut offset) = self.get_leaf()?;
    |                                   ----------------
    |                                   |
    |                                   the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                   in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:682:37
    |
682 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:682:37
    |
682 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> rope/src/rope.rs:682:22
    |
682 |                 let (pl, poffset) = self.prev_leaf()?;
    |                      ^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: all local variables must have a statically known size

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> rope/src/rope.rs:682:37
    |
682 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     ^^^^^^^^^^^^^^^^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:686:37
    |
686 |                 let (nl, noffset) = self.next_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:686:37
    |
686 |                 let (nl, noffset) = self.next_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:699:35
    |
699 |         let (mut l, mut offset) = self.get_leaf()?;
    |                                   ----------------
    |                                   |
    |                                   the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                   in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:699:35
    |
699 |         let (mut l, mut offset) = self.get_leaf()?;
    |                                   ----------------
    |                                   |
    |                                   the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                   in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:710:37
    |
710 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:710:37
    |
710 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> rope/src/rope.rs:710:22
    |
710 |                 let (pl, poffset) = self.prev_leaf()?;
    |                      ^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: all local variables must have a statically known size

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> rope/src/rope.rs:710:37
    |
710 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     ^^^^^^^^^^^^^^^^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:714:37
    |
714 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:714:37
    |
714 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error[E0308]: mismatched types
  --> rope/src/find.rs:92:9
   |
92 |         Some(r) => find_progress_iter(cursor, lines, pat, &|_| { Some(0) },
   |         ^^^^^^^ expected reference, found enum `std::option::Option`
   |
   = note: expected type `&std::option::Option<regex::Regex>`
              found type `std::option::Option<_>`

error[E0308]: mismatched types
  --> rope/src/find.rs:94:9
   |
94 |         None => {
   |         ^^^^ expected reference, found enum `std::option::Option`
   |
   = note: expected type `&std::option::Option<regex::Regex>`
              found type `std::option::Option<_>`

error: aborting due to 18 previous errors

error: Could not compile `xi-rope`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `xi-core v0.2.0 (file:///Users/federico/Documents/xi-editor/rust)`, intermediate artifacts can be found at `/Users/federico/Documents/xi-editor/rust/target`

Caused by:
  build failed

**Comment by cmyr** [comment]
@BaldEagleX02 looks like your `rustc` is out of date. The current minimum supported version is 1.26.

**Comment by BaldEagleX02** [comment]
Thank you, now it works! It compiled and ran! I updated my rust version to 1.27. I think you should add a useful feature in your code: make it search your rustc version and, if it's too old, it tells it to the user.

**Comment by cmyr** [comment]
@BaldEagleX02 that's what readme's are for. 😉 Happy you've got it working!
