### ISSUE TITLE
editor state for copy-and-paste (overwriting selection) confused by a backspace

### ISSUE THREAD

**Issue by pnkfelix** [google/xi-editor#75]
editor state for copy-and-paste (overwriting selection) confused by a backspace

I'm using a build from master branch, commit c6fa6b255bccc6ad8e3658843083cdc66282859b

When i start up the editor, and then type the following (where each keystroke is delimited by single quotes):

'0', '1', 'delete', '2', 'shift-leftarrow', 'shift-leftarrow', 'command-c', 'command-v'

(in other words, type the string "01", then delete the '1' and replace it with a '2', then select the full text "02" via the left arrow key; finally copy it to the clipboard and then paste it over the same selected text...)

I find, when I do this, instead of replacing "02" with "02" as I would have expected, the editor is replacing the string "02" with "00".

(There are other strange phenomena occurring I suspect are related to this.)

**Comment by pnkfelix** [comment]
I uncommented the `print_err!("from core {}", s);` line to ease observation of what's being transmitted over the wire.

Seems like the bug is contained to the `xi-core` crate, if I understand what I am seeing from the protocol correctly.

Here is the back-and-forth I witness:

```
to core: {"id":0,"method":"new_tab","params":[]}
from core: {"id":0,"result":"0"}

to core: {"method":"edit","params":{"method":"scroll","params":[0,20],"tab":"0"}}
to core: {"id":1,"method":"edit","params":{"method":"render_lines","params":{"first_line":0,"last_line":100},"tab":"0"}}
from core: {"id":1,"result":[["",["cursor",0]]]}

RPC latency = 0.62ms
to core: {"method":"edit","params":{"method":"click","params":[5,0,0,1],"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["",["cursor",0]]],"scrollto":[0,0]}}}

to core: {"method":"edit","params":{"method":"insert","params":{"chars":"0"},"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["0",["cursor",1]],[""]],"scrollto":[0,1]}}}

to core: {"method":"edit","params":{"method":"insert","params":{"chars":"1"},"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["01",["cursor",2]],[""]],"scrollto":[0,2]}}}

to core: {"method":"edit","params":{"method":"delete_backward","params":[],"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["0",["cursor",1]],[""]],"scrollto":[0,1]}}}

to core: {"method":"edit","params":{"method":"insert","params":{"chars":"1"},"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["01",["cursor",2]],[""]],"scrollto":[0,2]}}}

to core: {"method":"edit","params":{"method":"move_left_and_modify_selection","params":[],"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["01",["sel",1,2],["cursor",1]],[""]],"scrollto":[0,1]}}}

to core: {"method":"edit","params":{"method":"move_left_and_modify_selection","params":[],"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["01",["sel",0,2],["cursor",0]],[""]],"scrollto":[0,0]}}}

to core: {"id":2,"method":"edit","params":{"method":"copy","params":[],"tab":"0"}}
from core: {"id":2,"result":"01"}

to core: {"method":"edit","params":{"method":"insert","params":{"chars":"01"},"tab":"0"}}
from core: {"method":"update","params":{"tab":"0","update":{"first_line":0,"height":1,"lines":[["00",["cursor",2]],[""]],"scrollto":[0,2]}}}
```

In particular, that `"00"` in the last line looks pretty fishy to me.

**Comment by raphlinus** [comment]
Yup, this is a subtle logic error in `Engine::mk_new_rev`, specifically the transform of `deletes` through `rev.from_union`. It's fine when the edit contains inserts or deletes only, but not both. I'll come up with a fix soon.

Thanks for the minimal repro case, it was quite useful in tracking it down!
