### ISSUE TITLE
Side View is needed for xi-editor

### ISSUE THREAD

**Issue by subumm1** [google/xi-editor#78]
Side View (Inner View) is needed for xi-editor for developing other features.

example / Find, Folder View, Console, ...

It should be designed for reuse.

NSOutlineView is good option.

But How about make simple SideView which can shown at left, right, down, top,

And extends SideView to develop complex work?

It should be more comfortable for developing plugin.

**Comment by cmyr** [comment]
This is a frontend implementation detail; issues can be opened against specific frontends.
