### ISSUE TITLE
Editor aware of Rust copy/borrow when editing .rs files

### ISSUE THREAD

**Issue by luca-i** [google/xi-editor#790]
It would be nice if the editor could have a special mode when editing Rust source code to highlight borrow / copy behavior.
The syntax highlight engine could traverse the AST and color identifiers with a special color when they are borrowed or copied, so that it would be easier for the programmer to spot where the identifier becomes unusable (in case of copy).
I am pretty new to Rust and I feel its memory management model isn’t all that easy to grasp. If the editor could help a little, it wouldn’t hurt.

(Of course I don’t know enough Rust or its compiler internals to judge if what I’m asking is possible or not)

**Comment by cmyr** [comment]
This is an interesting idea, but it's pretty far outside the immediate scope of this project. Something like RLS _will_ tell you when you've tried to use something that has already been moved, and show you an error; I'm not sure if this is exactly what you're looking for, though?

Also I believe you're confusing 'move' and 'copy'. A value that can be 'copied' (which implements the `Copy` trait) can be moved without borrowing, and used afterwards; this is the behaviour, for instance, of the number types, e.g.

```rust
use std::fmt::Display;

fn main() {
   let a_string = String::from("I'm a string");
   let count = a_string.len(); // usize
   move_print(count);
   move_print(a_string);
   println!("len: {}, string {}", count, a_string); // fine for count, error with a_string
}

/// Takes ownership of its argument and prints it.
fn move_print<T: Display>(thing: T) {
    println!("move print {}", thing);
}
```

In any case, I think you'll find that as you write a bit more Rust some of these things will click. There are definitely tricky parts of the ownership model, but over a few small projects I think you'll start to get a feel for it; and if you get stuck, a great resource is the #rust-beginners channel on irc.mozilla.org.

**Comment by jansol** [comment]
This would definitely be a neat feature! For example when the cursor is within a variable (similar to definition on hover), it could highlight where ownership is transferred and where the variable is finally dropped.

As the saying goes, everything is possible - the impossible just takes a bit longer. This feels like it should be part a language server if that was designed around rust. I don't know how flexible the LSP protocol is for such things, but if it would allow something like this I think this should definitely be part of the RLS. On the practical side, this would essentially amount to running running the borrow checker and extracting the variable's life cycle for display.

As mentioned above, this is not quite in scope for xi itself though.
