### ISSUE TITLE
Editing the beginning of a large line file is VERY slow

### ISSUE THREAD

**Issue by michaelAndersonCampingWorld** [google/xi-editor#80]
I tried editing a large css source map, one that Atom was choking on in xi-editor. Opening it was instantaneous, but I was unable to interact with the file at all without significant delay. Left-right arrows brought delay and typing anything brought delay.

This seems like a bug since the stated purpose of this editor is jank-free editing. I can provide the file, if needed, in a gist.

**Comment by raphlinus** [comment]
I'm pretty sure I know what this is. The `CTLineGetOffsetForStringIndex` call in [EditView.swift](/google/xi-editor/blob/master/XiEditor/EditView.swift) seems to take an inordinate amount of time when lines get very long. This seems to be a problem in CoreText. I do have plans to address it - it's basically a trivial calculation when the line is ASCII and the font is monospaced, so I'd like to detect that case and bypass CoreText.

And yes, it's reasonable to consider performance issues like this a bug.

**Comment by cmyr** [comment]
Closing this, keeping #210
