### ISSUE TITLE
if xi support multi edit mode like vim?

### ISSUE THREAD

**Issue by hh9527** [google/xi-editor#85]
i know that is not available yet for now. my question is "is it possible to implement a vim-like editor with plugin?"

**Comment by Lucasosf** [comment]
I would like to use something like the vim modes too.

**Comment by dpc** [comment]
I'd just like to add, that if the effort to support it is to be made, please remember that Vim is not the only way to work with modes. I actually enjoyed kakoune improvement over original Vim ways.

**Comment by cmyr** [comment]
@dpc I agree, kakoune seems like a really interesting development. I would hope any modal model eventually implemented for xi would be extensible enough to play around with other possibilities. :)

**Comment by dotancohen** [comment]
+1 support for a VIM mode. Xi is the first editor that I've been excited about in over a decade, but without a VIM mode it would be useless to me.

**Comment by raphlinus** [comment]
I'm not sure whether a plugin is the best place to implement vim-style modal editing (I think it might require tighter binding with the front-end than I have in mind for plugins), but in any case it's on the roadmap. It will require community participation if it will be implemented any time soon, though.

**Comment by tarvos21** [comment]
@raphlinus, happy to hear that, I find XiEditor exciting on macOS.

**Comment by JESii** [comment]
+1 for vim... my fingers do the talking

**Comment by cmyr** [comment]
Closing as a dupe: #93 will be the tracking issue for modal editing support.
