### ISSUE TITLE
Leverage NSDocument

### ISSUE THREAD

**Issue by npgm** [google/xi-editor#88]
NSDocument supports the multiple window model a la TextEdit. This will solve #15 and I believe it will solve #57 when Sierra adds native tab support. In the meantime there are [solutions](http://cutecoder.org/programming/window-multiple-documents/) to implement tabs with NSDocument. 

More context on doc based apps: 
https://developer.apple.com/library/mac/documentation/DataManagement/Conceptual/DocBasedAppProgrammingGuideForOSX/Introduction/Introduction.html

I can provide a PR.

**Comment by raphlinus** [comment]
I'm open to the idea, but when I looked at NSDocument last, there seemed to be a number of assumptions that didn't hold well. For example, actual loading and storing of files happens in the core, not in the Cocoa app. But I can't say I'm expert on the tradeoffs.

If we're not going to wait for Sierra, MMTabView looks really nice. But maybe waiting for Sierra is OK, especially if it's usable in a multi-window (but not multi-tab) form before then.

I'd absolutely consider a PR, if you think you can subclass NSDocument in a way that is consistent with xi-core doing most of the functionality listed in that linked doc.

(Sorry for taking so long to respond, have been busy)

**Comment by DivineDominion** [comment]
You can override the read and write methods of `NSDocument` subclasses with your own mechanisms (`readFromURL` and `dataOfType`, for example); this has to be done synchronously, though. I can imagine the method delegates to a RPC call which returns the contents. Is that still a problem?

**Comment by raphlinus** [comment]
@DivineDominion Yes, now that you point that out, I think it's exactly the problem. The _current_ implementation of loading and saving happens to be synchronous in the core (though the notification from front-end to core is asynchronous), but the plan is for it to very much not be. So I think that might break the NSDocument model.

Do we know if the Sierra tabs are available to non-NSDocument apps?

**Comment by porglezomp** [comment]
The docs say that NSDocument can save asynchronously (since 10.7), so that shouldn't be a problem. If you go to the [Doc Based App Programming Guide For OS X](https://developer.apple.com/library/mac/documentation/DataManagement/Conceptual/DocBasedAppProgrammingGuideForOSX/StandardBehaviors/StandardBehaviors.html) and read "Document Saving Can Be Asynchronous" it has the requirements.

**Comment by bjtitus** [comment]
I've got a branch with work on this + changes to Storyboards and static RPC types: https://github.com/bjtitus/xi-editor/tree/nsdocument%2Bstoryboards

Is that something you'd be interested in merging? If so, I can submit a PR.

**Comment by jansol** [comment]
@bjtitus I suggest just going for it, easier to comment on actual changes than hypothetical ones. It's also easier to track the change across repos that way. If it turns out to be a bad idea the PR can always be just closed without merging.
