### ISSUE TITLE
Core's applicability to non editor use-cases

### ISSUE THREAD

**Issue by stephanbuys** [google/xi-editor#89]
Hi, listened to the interview on New Rustaceans podcast, project sounds awesome. The persistent rope data structures and plugins sound super intriguing.

I'm coming from the log management world where we often process text through project such as logstash. Could a) the concepts behind xi be used effectively in a log management scenario (mutating events, marking them up, running pattern matching, etc); b) BIG leap :-) could xi-core even be forked/used for this?

Just a fun thought experiment for now...

**Comment by raphlinus** [comment]
My guess is that some of the lower level stuff could be useful, but not sure about the core as a whole, unless what you're doing is very similar to user-driven text editing. I do plan to publish the xi-rope crate to cargo, and hope it finds uses. It does need better documentation and maybe some cleanup, though.

**Comment by TyOverby** [comment]
I'm really interested in using the rope data structure for my own editor.  I can survive by copy/pasting your rope folder, but I'd love a crates.io release, even if it's unpolished.

**Comment by raphlinus** [comment]
Sure, no problem. I'll push it later this afternoon; I was basically
waiting on actual users.

**Comment by stephanbuys** [comment]
@raphlinus, awesome thanks. Do you have a link to a good resource (canonical?) that would allow grokking the benefits/costs of the rope data structure?

**Comment by raphlinus** [comment]
@stephanbuys Unfortunately, I didn't really find anything. The finger tree paper is one of the best on ropes, but it makes a whole bunch of Haskell assumptions.

The criteria for using a rope are roughly: Are your strings larger than 1MB or so (if they're consistently smaller, it's easier and usually fast enough to just copy contiguous strings)? Are you going to do a lot of edits? Do those edits not have guaranteed locality? Will you need to keep multiple copies of similar strings around? Do you need to share them across thread boundaries? All those things are true of xi-editor.

**Comment by stephanbuys** [comment]
@raphlinus thanks very much (again) - I'll try a couple of prototypes and report back if I end up using it. My gut is saying thats its a great solution for log management, especially as you can then 1) process larger batches of text (primary source) 2) in parallel 3) do so with multiple operations. Intuitively I think that for a subset of use-cases if would make the process blazingly fast.
