### ISSUE TITLE
GTK+ front-end efforts

### ISSUE THREAD

**Issue by eyelash** [google/xi-editor#92]
I found some motivation the last few days so I started a [GTK+ front-end for Xi](https://github.com/eyelash/xi-gtk). It does not handle input yet but it can open and display files. If you want to test it you need to have the `xi-core` executable in the same directory where you execute xi-gtk.
I will probably add some input handling so you can do some basic editing but I guess I won't have the time to maintain a full GTK+ front-end for years. However, I wanted to post this here so an official GTK+ front-end might be based on (or at least inspired by) my code. What do you think?
(@JesseFarebro I saw you opened a xi-gtk repo but there is no actual code in there)

Update: I have now added support for basic editing. So you can now type and select text with the mouse.

**Comment by raphlinus** [comment]
Very cool! I played with it and there are definitely rough edges, but it looks promising.

Would you like a link from the README?

**Comment by eyelash** [comment]
As I'm not sure how far I will take it (it also depends on how the core evolves) I leave it up to you whether you add a link in the README.
What rough edges have you found? There might be something that I'm not aware of.

**Comment by raphlinus** [comment]
If you open a file, then click and drag down, it highlights the first line and the line under the mouse, unhighlighting the ones in between. I've also triggered what seems to be an off-by-one error where sometimes draws the wrong line, or perhaps draws the right line but at a y offset one line too high. This is on Ubuntu 14.04.

On my Mac, there area more problems. The EditView window draws only the upper left quadrant (almost certainly a high dpi issue). Keyboard input doesn't work. I'm not too concerned about Mac support, but if it worked it would make it easier for me to keep the front-ends in sync.

**Comment by JesseFarebro** [comment]
@eyelash my implementation I hadn't committed was using Rust and the GTK bindings for Rust. Vala would be a good choice as well. 

@raphlinus I hope eventually we can have a XI organization where we can have an official GTK front-end with along with the core and Swift front-end. 

Vala will have better native support for GLib, Cairo and other GNOME technologies. I wish GTK was using Skia but that's a topic for another day. I was thinking of rewriting my implementation in Vala anyways so I'll just contribute to your repo for the time being.

**Comment by eyelash** [comment]
I thought about using Rust as well but the bindings are very young (and not yet stable) and I don't have much experience in Rust so it was easier to get something started in Vala.

**Comment by eyelash** [comment]
What about having one central EditView implementation using Skia and then the different native UIs built around that? This would probably also facilitate drawing custom stuff on the EditView from plugins.

By the way I fixed the high dpi and multiple line selection issues. There is still one issue where I scroll through a large (1700 lines) file and suddenly I don't get any responses from the core anymore. Not sure whether is is a core or a front-end issue.

**Comment by JesseFarebro** [comment]
@eyelash that could be a good idea, Skia is pretty battle tested now being the default renderer in Chrome and Firefox. @raphlinus does Skia meet your performant font rendering requirements?

**Comment by raphlinus** [comment]
@JesseFarebro My gut feeling is that, on most platforms anyway, the native text rendering will outperform a Skia-based approach. My other concern is that a Skia-based text renderer is a huge undertaking if it handles all of Unicode well (complex scripts, bidi, color emoji, etc). Something that just draws ASCII is not too hard, but that's not really my goal.

That said, if someone wants to write a cross-platform text drawing canvas and use it as the basis of a front-end, I certainly won't stop them. If it's better, excellent. I just have very little interest in taking that on myself.

**Comment by critiqjo** [comment]
> handles all of Unicode well (complex scripts, bidi, color emoji, etc).

Is Xi meant to go beyond being a developers' editor -- may be even support proportional fonts one day?

If it is limited to a dev-editor, then there would rarely be a need to render such characters, and may be even get away with the Vim way of displaying stuff like `<88>` etc. I feel like such rich text handling belongs somewhere else.

**Comment by Spencer-H** [comment]
If it's ever used for web development, it may very well need to handle stuff like that.

**Comment by critiqjo** [comment]
> If it's ever used for web development, it may very well need to handle stuff like that.

Sure! Handling such text might be very typical in certain circumstances. I was just wondering how a word such as `ചൊറിഞ്ഞോ` (see image below) could be rendered in a monospace-grid.

![latest-screenshot](https://cloud.githubusercontent.com/assets/1436441/18030174/b1cdb696-6cca-11e6-8c8d-211a0c06a00f.png)

Note that it contains only 3 letters -- the first 2 are combinations of 2 code points each and the 3rd extra-wide letter of 4 code points. I just find it unrealistic to provide support for complex South/South-East Asian scripts without proportional fonts. And If proportional font rendering is targeted, then the whole document would have to be rendered to correctly determine the scroll position (only when text-wrap is enabled, I guess). That may in turn restrict the design to take a route where very long lines can't be efficiently handled. _These are just my (read naive) speculations. I would be happy to be proven wrong._

**Comment by cbreeden** [comment]
We might be able to learn a little bit from how TeX handles line wrapping.   Internally TeX just keeps track of every glyphs dimensions, then references formulas for kerning and linebreaking.  Unfortunately, I think this is somewhat of a global analysis.  At least we could be restrained to applying such formulas on a paragraph level--at least during live updates since previous paragraph rendering would be independent-- and not need to worry about page breaking as well (which truly is a global calculation as far as I know).

But you could also imagine that there would be a fast lane for those cases where the font is monospaced.  Don't know if that's a good idea, I was just thinking out loud.

**Comment by critiqjo** [comment]
@cbreeden There is a problem with that approach though. By default, only the back-end has complete knowledge of the document, and the front-end is supposed to only see as much as needed for rendering. But determining how many lines/characters to send to the front-end will require information about the actual glyphing of code-points. This probably means that all text need to be looped through the front-end at least once (and again whenever font settings are changed).

**Comment by jansol** [comment]
Closing as there are multiple active gtk frontend projects mentioned in the readme.
