### ISSUE TITLE
RPC notification from backend to frontend

### ISSUE THREAD

**Issue by rkusa** [google/xi-editor#99]
If I understood the backend correctly, the current message flow is as follows:

Text Edit → RPC notification from frontend to backend  → Tabs::do_rpc -> Editor::do_rpc → Editor::render – [if is dirty] → RPC update notification from backend to frontend

Are there already plans to where to plug in other notifications from backend to frontend, e.g. alerts? Since the editor does not have direct access to the `rpc_peer` currently, the editor can only send notifications from its render method (which receives the `rpc_peer` from the tab context). I am considering doing a PR, but want to make sure that it goes into the right direction.

**Comment by raphlinus** [comment]
You're quite right; since the plugin sends notifications asynchronously, the editor needs a way to notify the front-end other than inside a call from Tabs. So you're right, it needs to hold a reference to the `rpc_peer`.

I think it needs to be weak reference, because the peer's handler holds a strong reference to the tabs, which in turn owns the editor. The same will probably be true of the link between the editor and the plugin (the editor will need to hold a reference to the plugin to notify it when the content changes).

A PR would be welcome!

**Comment by rkusa** [comment]
Thanks for the feedback! I'll try to integrate it

**Comment by rkusa** [comment]
I played around with different ideas of where and how to implement this.

My feeling is to try to avoid using `Arc<T>`, `Rc<T>` and Co if possible. This is why I actually like the current implementation where a reference to the `rpc_peer` is only handed out purposely.

That being said, my current proposal would be to handle this similar to how receiving the RPC messenges work. I'll try to illustrate the general outline:

- each tab has a queue of pending notifications
- `main.rs` spawns a thread that is waiting for content in these queues
- if there is content, it will hand out the `rpc_peer` for sending out the notification

This would also allow to prioritize notifications to the active tab and maybe even suppress (or delay) notifications to tabs in the background.

However, maybe it is not possible to completely avoid using `Arc<T>` or something similar, because all editors propably need to share the same `Condvar` to notify the thread of new content in the queue.

(Since I am not really experienced in Rust, it is possible that I am totally wrong—if this is the case, please tell me! 😉)

**Comment by raphlinus** [comment]
I don't have a very strong feeling about `Arc<Mutex<T>>` vs a queue. The latter feels maybe cleaner and more decoupled, but I think the former has the potential for slightly less overhead; in my initial measurements, passing an object from one thread to another via a channel is about 3-5µs, while an uncontended arc/mutex is going to be maybe a few hundred ns. I don't know yet whether this will make an actual difference in performance; likely not.

Bottom line, I'm sure it's possible to do it either way. It's just that it's fairly clear to me how to do it with Arc/Mutex, and less so with queues.

Also keep in mind that at some point the relationship between tab and buffer won't be 1:1, that in the future there may be multiple views of a single buffer. When that happens, we'll want to send notifications to all tabs open on a buffer. Changing the configuration, ie adding or deleting a tab, is also something I can easily see how to do with mutexes, less clear with channels.

But I'll happily take any PR that gets this working in a reasonably clean way and with no serious performance problems. It's always possible to fine-tune later.

**Comment by rkusa** [comment]
Thanks for the feedback! I've moved the discussion into the PR.
